### ISSUE TITLE
[Feature Request] Sort Priorities when **Default Input** is Empty

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#100]
Hello @tadashi-aikawa !!!!!

Let em try to explain  my FR ...

I noted that when AQS modal is triggered by Custom Command that has an **empty** Default Input the Priorities rules is not been applied to the AQS modal

### Real Example

**Example A:** This is my Custom Search without an empty Default Input

📸 Setting
![image](https://user-images.githubusercontent.com/85180696/187676236-d6525229-2890-4e03-ac30-c1ade5953a69.jpeg)

📸 AQS Modal
![image](https://user-images.githubusercontent.com/85180696/187676253-5ad66227-ab42-4f6d-9c82-ffd16c8fcb97.jpeg)

*Result* 100% working perfect
5A - 5B - 5C - 5D - 5E - 5F - 5G

---

**Example A:** This is my Custom Search with an empty Default Input

📸 Setting
![image](https://user-images.githubusercontent.com/85180696/187676309-53c961b9-75c6-4757-af30-07fb9c4808f9.jpeg)

📸 AQS Modal
![image](https://user-images.githubusercontent.com/85180696/187676345-4172389c-b519-42b0-a941-79377d41d65c.jpeg)

*Result* The Priority is not been applied to the AQS Modal

5G - 5A - 5F - 5E - 5D - 5B - 5C

---

Maybe I am missing some setting, but would be amazing if we could apply the Priority to the AQS modal when the default input is empty :)

I think this FR have some relation to #81 

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @FelipeRearden :)

I'll implement it in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/101).

**Comment by FelipeRearden** [comment]
> I'll implement it in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/101).

Thank you very much @tadashi-aikawa !!!!!!!!!!!!!!!!

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Released in [7.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0-beta1) 🚀

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0) 🚀
