### ISSUE TITLE
FR: enable fuzzy search on search command

### ISSUE THREAD

**Issue by svonjoi** [tadashi-aikawa/obsidian-another-quick-switcher#102]
It would be cool if i could enable fuzzy search method on specific search command, like in default quick switcher

![image](https://user-images.githubusercontent.com/58810368/188277234-baa523a9-059a-4286-95fb-117f0e33d218.png)

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @svonjoi :)

So far, I am not going to make the search fuzzy. There are reasons in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/88.

However, if many users want it, I'll consider implementing it. So let me set the status of this issue to "gathering interest".

**Comment by svonjoi** [comment]
sorry i didnt search in discussions before posting this. Thanks

**Comment by tadashi-aikawa** [comment]
No worries :) It is hard to reach there from the title of the discussion 😅

**Comment by tadashi-aikawa** [comment]
@svonjoi @danrthompson 
Thanks for waiting! I've released it in [v8.10.0-beta1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0-beta1) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.🙏

**Comment by svonjoi** [comment]
hi bro, thanks you for implementing this :)

I think its very cool because you can also "customize" the fuzzy search behaviour, playing with <sort priorities>. Btw, how I have to configure the sort priorities in order to make exactly the same behaviour as in native quick switcher?

Also, i think it would be great if matched letters become bold as you type, like in native one

![fuzzytadashi](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/58810368/669f20b6-b556-4755-a2e3-d3cd1eb15ec6)

Thanks again :)

**Comment by tadashi-aikawa** [comment]
> how I have to configure the sort priorities in order to make exactly the same behaviour as in native quick switcher?

I do not intend to have the same sorting order and do not think it is necessary. So please control it with settings.

> Also, i think it would be great if matched letters become bold as you type, like in native one

Please see the following issue.

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/151

**Comment by svonjoi** [comment]
@tadashi-aikawa Nice, thank you

**Comment by tadashi-aikawa** [comment]
Hi, @svonjoi :)

I have released [v8.10.0-beta3](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0-beta3). That version has some improvements about the fuzzy match.

For details, please see the [discussion](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/167).

**Comment by tadashi-aikawa** [comment]
Fix a few bugs in [v8.10.0-beta4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0-beta4).

**Comment by tadashi-aikawa** [comment]
Released in [v8.10.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0) 🚀
