### ISSUE TITLE
request: search for only folders?

### ISSUE THREAD

**Issue by zeltak** [tadashi-aikawa/obsidian-another-quick-switcher#103]
Hi!

many times I have the need to jot a note in a specific folder. is there a way to limit search just to folders with AQS?

thx a lot!

Z

**Comment by tadashi-aikawa** [comment]
@zeltak 
You can search the specific folder by inputting `folder_name/`. The last `/` is important.

**Comment by zeltak** [comment]
thx so much @tadashi-aikawa !

I actually tried that but it can't seem to present an option to jump to the folder or even show the folder, ie

![CleanShot 2022-09-04 at 15 22 39](https://user-images.githubusercontent.com/498410/188313309-cfae818d-dbb4-4377-bea4-171eec8962b8.png)


what am I doing wrong?

as always many thx for your amazing work, your multiple plugins are just pure joy :)!!!

**Comment by tadashi-aikawa** [comment]
@zeltak 
It looks like it has no problems for me 🤔 

![image](https://user-images.githubusercontent.com/9500018/188313605-bab4d3d5-aa3e-498b-b666-895de6d1c895.png)

There are 12 files in the "Obsidian" directory and the same with the result in AQS.

**Comment by zeltak** [comment]
ahh maybe I wasn't clear enough. :) I dont want to see all files in the `obsidian/` directory but jump to the root level of the `obsidian/` directory. is that possible at all currently?

![CleanShot 2022-09-04 at 15 56 19](https://user-images.githubusercontent.com/498410/188314673-70ea79b7-840f-4d31-a3ee-d9bf48d079b4.png)

Does that makes sense?

thx so much 

Z

**Comment by tadashi-aikawa** [comment]
Thank you for your description. I understood 👍 

In your case, is it better to add a new feature similar to "Move file to another folder" command?

![image](https://user-images.githubusercontent.com/9500018/188316472-e82c7cbb-3d68-425c-9125-caa6fdc41fbf.png)

It will show the directory on the file explorer (in Obsidian) instead of moving a file. (If possible...)

**Comment by zeltak** [comment]
yeah that sounds perfect!

thx so much for considering this!

best regards

Z

**Comment by FelipeRearden** [comment]
Hello @zeltak  and @tadashi-aikawa 

Sorry to step into this FR. I use wanna share 2 ideas about this topic 💡

> In your case, is it better to add a new feature similar to "Move file to another folder" command?
>
> It will show the directory on the file explorer (in Obsidian) instead of moving a file. (If possible...)

## Idea 1️⃣ 

How about an additional command that open the **note that is focused/selected** in the AQS in  the File Explorer ???

This way we have all scenarios covered: Directory and File :)

## Idea 2️⃣

@tadashi-aikawa how about opening the file explorer menu context (mouse right click) **after** showing the File Explorer ???

![883EA14B-CC3A-45B9-A19E-60AEA4F56DCB](https://user-images.githubusercontent.com/85180696/188335786-b1a8543e-803c-4b11-9993-4ce5f7edd840.jpeg)

My idea is to automate the workflow of using File Explorer to become 100% keyboard friendly.

From  my workflows, 99% of the time that I open File Explorer, is to open  the menu context to **manage** the File or directory:
- Delete 
- Rename
- Make a Copy (Duplicate)

---

Have a great day !

**Comment by ShravanSunder** [comment]
It would be great to search for a folder and jump to it @tadashi-aikawa 
and thanks for the amazing plugin

**Comment by tadashi-aikawa** [comment]
OK. I'll implement the following specification 👍 

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/103#issuecomment-1236344492

**Comment by N3C2L** [comment]
> OK. I'll implement the following specification 👍
> 
> [#103 (comment)](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/103#issuecomment-1236344492)

@tadashi-aikawa 

May I ask if this is already implemented? If yes, please forgive me if I can't find the command for it.

**Comment by tadashi-aikawa** [comment]
@N3C2L 
No, unfortunately, it has not been implemented yet, but it is planned.

**Comment by tadashi-aikawa** [comment]
@zeltak @FelipeRearden @ShravanSunder @Kiss-World @N3C2L
Thank you for your patience.

I have released this feature in [v11.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.5.0) 🚀

**Comment by ShravanSunder** [comment]
thank you!
