### ISSUE TITLE
[Feature Request] Sort by created date 

### ISSUE THREAD

**Issue by rapatel0** [tadashi-aikawa/obsidian-another-quick-switcher#104]
Ideally we could add creation date to the sort priorities in either descending or ascending order. 

This would be useful for meetings where the most recent meetings would be more useful to see

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @rapatel0 :)

I'll consider it 👍

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0-beta5) 🚀

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0) 🚀
