### ISSUE TITLE
[Bug] change `Mod -` hotkey

### ISSUE THREAD

**Issue by kometenstaub** [tadashi-aikawa/obsidian-another-quick-switcher#106]
Could you please change the `Mod -` hotkey for opening a file in a new horizontal pane?

Currently it coincides with the global Zoom out functionality in Obsidian. That means that when I use it to open a note in a new horizontal pane, Obsidian itself zooms out.

**Comment by kometenstaub** [comment]
Maybe `Mod h` for horizontal panes and `Mod v` for vertical panes could be used?

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @kometenstaub :)

The problem seems that it can't prevent the key event. I'll investigate it.

**Comment by tadashi-aikawa** [comment]
@kometenstaub 
It would fix in [v7.0.0-beta7](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0-beta7) 🚀 

If you use BRAT, Could you confirm it to fix the bug?

**Comment by kometenstaub** [comment]
Thank you so much, it works! 🥳
