### ISSUE TITLE
Which search is considered to be the "default" one?

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#107]
A few people asked me to add support for AQS to my [default new tab page plugin](https://obsidian.md/plugins?id=new-tab-default-page), and I was wondering which search should be considered the default one that should be triggered? I previously implemented "Recommended Search", but I noticed that when resetting the new AQS searches, there is no recommended search anymore?

**Comment by tadashi-aikawa** [comment]
Case by case. I use both "Recent search" and "File name search" for my case.

**Comment by chrisgrieser** [comment]
hmm. I'll use "Recent Search" then, probably makes more sense for a new tab page, too. Thanks!
