### ISSUE TITLE
[FEAT] Support preview feature in Landmark search views/ other search views

### ISSUE THREAD

**Issue by Quorafind** [tadashi-aikawa/obsidian-another-quick-switcher#110]
RT, now we have preview feature in GREP search view. If it possible to preview note in other search views?

![image](https://user-images.githubusercontent.com/13215013/192184508-6af3fa20-676c-4ce1-93e3-51105abe2b62.png)

_Originally posted by @Quorafind in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/108_

**Comment by tadashi-aikawa** [comment]
Coming soon..!

https://user-images.githubusercontent.com/9500018/209423019-77aad0ff-13ce-4d13-a8d0-ac0587d4e92b.mp4

**Comment by Quorafind** [comment]
Nice

**Comment by tadashi-aikawa** [comment]
@Quorafind 
Released in [v7.6.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.6.0) 🚀
