### ISSUE TITLE
grep not working?

### ISSUE THREAD

**Issue by jchenibm** [tadashi-aikawa/obsidian-another-quick-switcher#113]
I am using Mac and installed ripgrep which is on system PATH. When I call the grep command, it still asked to install and configure ripgrep.

Any thing broken or I missed some thing? Thanks!

**Comment by tadashi-aikawa** [comment]
Did you restart OS after installing ripgrep? If you did, and not working yet, please set the absolute path of ripgrep to the option. (ex: `/home/tadashi-aikawa/bin/ripgrep`)

![image](https://user-images.githubusercontent.com/9500018/193963740-826dd84d-88f5-46cb-8362-99ed23a88ee5.png)

**Comment by Quorafind** [comment]
@Archie-2021 You can try opening Powershell, input `rg` and then enter to see if the rigrep is installed correctly.

**Comment by Archie-2021** [comment]
> @Archie-2021 You can try opening Powershell, input `rg` and then enter to see if the rigrep is installed correctly.

yes, I tested the ripgrep. `rg --help` command in cmd and it works. My main question is how to set it up in there first place. Where should I say to the system that it is a ripgrep search?
