### ISSUE TITLE
UI looks off

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#114]
On 0.16.5 the UI of the switcher looks kina off:
<img width="716" alt="image" src="https://user-images.githubusercontent.com/44113468/194716184-eeb67919-273a-4b48-a121-96906dfcdc64.png">

**Comment by tadashi-aikawa** [comment]
Thank you for your bug report! I'll fix it 👍

**Comment by tadashi-aikawa** [comment]
Fixed in [v7.1.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.1.1) 🚀
