### ISSUE TITLE
New Custom search added no longer work

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/obsidian-another-quick-switcher#115]
Recently when I add a new search to the list it doesn't work (It shows the command prefix and the related tag I have set correctly) but shows nothing in the results. The top buttons also don't work . It is looking like this, Maybe it is broken after the update to Obsidian 1.0 and I am just noticing it right now. It is very weird, I deleted a search and recreated exactly like it was before but it doesn't work.

A screenshot of how it looks like right now with top buttons being dark and not working.

![image](https://user-images.githubusercontent.com/85870778/195978072-bbb64b11-b24c-45dc-9609-398ef7864446.png)

It is recognizing the command prefix but return nothing eventho there are hundreds of notes with this tag

![image](https://user-images.githubusercontent.com/85870778/195978189-48fffe9b-be34-4e72-b5a5-9a7519b5e319.png)

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
You should enable `Tag` in the `Search by` option.

**Comment by Archie-2021** [comment]
> @Archie-2021 You should enable `Tag` in the `Search by` option.

I see, Those dark buttons are clickable. The look of them is misleading, like they were disabled by some other settings.

Thanks

**Comment by tadashi-aikawa** [comment]
Sure. I'll add the description to `Search by` option. thanks :)

**Comment by tadashi-aikawa** [comment]
Released in [v7.1.2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.1.2) 🚀
