### ISSUE TITLE
FR: New Command – switch between currently open tabs

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#116]
With Obsidian 1.0, you can get a list of open tabs like in the browser by clicking on this button here: 
<img width="273" alt="Pasted image 2022-10-16 11 28 35" src="https://user-images.githubusercontent.com/73286100/196028217-189e90c2-b5d0-4ca5-a7ac-cf6e8455d7da.png">

However, that requires the mouse ;)
So it would be useful, if AQS could add such a tab switcher that can be used solely with the keyboard.

**Comment by kometenstaub** [comment]
I would also appreciate that feature :)

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @chrisgrieser (@kometenstaub ) :)

In my case, "Recent search" satisfied the demands. Could you tell me the advantages of "switch between currently open tabs" feature compared to "Recent search"?

**Comment by rapatel0** [comment]
Recent search doesn't. The switcher doesn't show currently open pages, so recent search comes up empty

**Comment by tadashi-aikawa** [comment]
Why do you need to show the current page in the result of the Recent search? I think there is no need because The page is already opened and activated.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.

**Comment by svonjoi** [comment]
> In my case, "Recent search" satisfied the demands. Could you tell me the advantages of "switch between currently open tabs" feature compared to "Recent search"?

I use obsidian as just an vim editor, and open obsi functionallity with floating window like backlinks list, live heading list, search in file and search in vault - all of these are functionallities from this plugin that is awesome, but the one thing missing is ability to trigger list of panes in floating window in order to hide panes from GUI and reach the max focus on what i working on

currently workaround i found is [this plugin](https://github.com/digitalsignalperson/obsidian-rofi-helper) but it shows all obsidian panes across all obsidian instances

**Comment by tadashi-aikawa** [comment]
That makes sense. If other people need it, I'll consider it.

**Comment by tadashi-aikawa** [comment]
Coming soon...

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/97cf7c44-b215-44ce-92e5-77fed1ff5362)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser @kometenstaub @rapatel0 @svonjoi 
Released in [v11.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.1.0-beta1) 🚀 

If you set the 'Search target' option to 'opened file', only files opened in the current window will be displayed as suggestions.

If you use BRAT, I would appreciate it if you could check it out before the official release.

**Comment by svonjoi** [comment]
working nice, thanks bruhh

**Comment by tadashi-aikawa** [comment]
@chrisgrieser @kometenstaub @rapatel0 @svonjoi
Released in [v11.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.1.0) 🚀
