### ISSUE TITLE
FR - Grep only in current folder

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/obsidian-another-quick-switcher#117]
Please add a command to only Grep in the folder of active note.

There are many customizations possible to add to this Grep command. Most importantly is to choose which subdirectory to search. And the most urgent and useful one among those is to be able to search into the current folder. That would allow a vim '/' like search in a document divided into smaller notes.

Thank you for this great plugin

**Comment by tadashi-aikawa** [comment]
Thank you for creating the issue :)

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
Do you use BRAT? If so, I will release 7.2.0-beta1, and it would be great to confirm the feature as expected.

**Comment by Archie-2021** [comment]
> @Archie-2021 Do you use BRAT? If so, I will release 7.2.0-beta1, and it would be great to confirm the feature as expected.

I do use BRAT, but only if I have to, Is switching to BRAT is going to remove my setiing on my main vault? If it is just for testing I can install it on a new vault using BRAT.

**Comment by tadashi-aikawa** [comment]
Released in [v7.2.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.0-beta1) 🚀 

@Archie-2021 
Good 👍 

> Is switching to BRAT is going to remove my setiing on my main vault?

It will not remove your settings, but creating a new vault and confirming it is more safety.

**Comment by Archie-2021** [comment]
> Released in [v7.2.0-beta1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.0-beta1) 🚀
> 
> @Archie-2021 Good 👍
> 
> > Is switching to BRAT is going to remove my setiing on my main vault?
> 
> It will not remove your settings, but creating a new vault and confirming it is more safety.

Sorry for replying a bit late, Got some issues with my laptop.

I tested it and it looks fine at my end too, Thank you for making this possible, I still think there is a lot of friction in searching the current directory. There is no autocomplete (keyboard only) way to insert `<current_dir>`. One idea is to add Shortcuts to be set for special paths like this, meaning adding it to grep dialog or something like that.Another one can be even shorter placeholders for special paths and adding autocomplete, or maybe adding favorite paths somewhere. There are a lot of possibilites.

Thanks again

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
Thank you for your confirming :)

> There is no autocomplete (keyboard only) way to insert <current_dir>. 

That's so weird. Can't you auto-complete `<current_dir>` like the following mp4? (type `<` or `cur` etc..)

https://user-images.githubusercontent.com/9500018/197332844-47ccec20-5362-4efc-8435-ec61e3374ff0.mp4

**Comment by Archie-2021** [comment]
I thought you used the mouse for autocompeletion. What key do you use? Tab (when diabled from original search keybinding) is switching between path and search TextBox. What should I press?

**Comment by tadashi-aikawa** [comment]
> What key do you use?

I use `Tab`. But, as you said, setting another hotkey to `search` is necessary. (That's not so good).

The "Grep dialog" can keep a path value even after closing the dialog. So I thought the hotkeys, as you suggested, might not be needed. 

> One idea is to add Shortcuts to be set for special paths like this, meaning adding it to grep dialog or something like that.

I like the above idea. If you want to, I'll add the hotkeys like the following.

- Sets `<current_dir>` to the path input
- Clear the path input

**Comment by Archie-2021** [comment]
> > What key do you use?
> 
> I use `Tab`. But, as you said, setting another hotkey to `search` is necessary. (That's not so good).
> 
> The "Grep dialog" can keep a path value even after closing the dialog. So I thought the hotkeys, as you suggested, might not be needed.
> 
> > One idea is to add Shortcuts to be set for special paths like this, meaning adding it to grep dialog or something like that.
> 
> I like the above idea. If you want to, I'll add the hotkeys like the following.
> 
> * Sets `<current_dir>` to the path input
> * Clear the path input

Yeah I like the idea too, that would be very nice

One other idea that just came to me is to use `.` and `..` inside path to specifying relative paths like in shell. So `<../.>` would search one folder above current path , etc.

Thanks

**Comment by tadashi-aikawa** [comment]
Released in [v7.2.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.0-beta2) 🚀

@Archie-2021
Please confirm the new features 🙏

**Comment by Archie-2021** [comment]
> Released in [v7.2.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.0-beta2) 🚀
> 
> @Archie-2021 Please confirm the new features 🙏

Yeah it works fine on my end too, Very nice, Thanks.

Are you planning to bring it to the main branch too or it needs more testing? Am I am looking for to see it on my main vault.

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
Soon 👍

**Comment by tadashi-aikawa** [comment]
Released in [v7.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.0) 🚀

**Comment by Archie-2021** [comment]
> Released in [v7.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.0) 🚀

Works like a charm.

Thank you very much 🙏
