### ISSUE TITLE
Is it possible to jump to the target?

### ISSUE THREAD

**Issue by jerviscui** [tadashi-aikawa/obsidian-another-quick-switcher#119]
Is it possible to jump to the target location when opening a file?

For example, if the header matches a file, click to jump to the header automatically

**Comment by jerviscui** [comment]
Yes, just like the jump function by Quick switcher++.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.

**Comment by tadashi-aikawa** [comment]
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/pull/142 will resolve this issue.

**Comment by tadashi-aikawa** [comment]
@jerviscui 
Released in [8.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.5.0) 🚀
