### ISSUE TITLE
Feature Request: Emacs-like Navigation Up/Down(Ctrl+P/N)

### ISSUE THREAD

**Issue by annenpolka** [tadashi-aikawa/obsidian-another-quick-switcher#12]
One thing that is in Quick Switcher ++ and I miss is the Ctrl+P/N (Up/Down) navigation.
This can be done with AutoHotkey, but it is less frictional for me if it is supported by this plugin.

**Comment by tadashi-aikawa** [comment]
@annenpolka 
Thank you for creating Feature Request!

It sounds good. I'll try it :)

**Comment by tadashi-aikawa** [comment]
@annenpolka 
I have released as [v1.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/1.5.0) 👍

**Comment by annenpolka** [comment]
Looks nice! Thank you for your great work!

**Comment by jzhang-brex** [comment]
Consider add this to README.md

**Comment by tadashi-aikawa** [comment]
We can know the keymaps on the switcher at

![image](https://user-images.githubusercontent.com/9500018/151895994-67a40c11-a37c-40ee-bfcb-fb53d3ee326d.png)
