### ISSUE TITLE
Bug: [Linux] Grep search won't return any results

### ISSUE THREAD

**Issue by lguenth** [tadashi-aikawa/obsidian-another-quick-switcher#120]
Hey Tadashi!
I've noticed that after the latest update (or so I think), the grep/rg search isn't working any more. Regular `rg` commands in my terminal still work. 

I tried different casing, choosing a specific folder, but no matter what I search for, there are no results. Steps to reproduce would be to open grep search, put anything into it and hit `Tab`. I only changed the Appearance settings and set hotkeys, I think the rest of my settings are default.

![image](https://user-images.githubusercontent.com/69049131/199468395-46ce632c-2fa4-4a38-999a-65f873580f9c.png)

I saw someone mentioning it on Discord, too, so that's why I'm filing a bug report.

Thanks for the plugin and its many possibilites!

**Comment by lguenth** [comment]
@tadashi-aikawa 
Yeah, I can reproduce it in the sandbox vault. So, open sandbox, install plugin, call "AQS: Grep" from the command palette, try to search something. No results for "help" or "Obsidian" etc. Even if I use the full path to my rg binary in the settings. Not getting any errors, even with more verbose logging enabled.

Some system info:
I'm on Obsidian `v1.0.3` with the `v1.0.3.` installer, AQS version `7.2.1`, running on Linux, specifically vanilla Ubuntu 22.04 Jammy Jellyfish with Obsidian installed through the official AppImage.

**Comment by tadashi-aikawa** [comment]
@lguenth 
Thanks for details :)

I could reproduce it on Ubuntu 22.04 LTS created by Multipass on Windows 👍

**Comment by tadashi-aikawa** [comment]
Ah...

```ts
const p = "/home/hogehoge"
console.log(normalizePath(p))
// home/hogehoge
// ↑ wrong absolute path
```

```ts
const p = "C:/Users/syoum/work/minerva"
console.log(normalizePath(p))
// C:/Users/syoum/work/minerva
// ↑ Windows path doesn't begin with `/`, so was not no effects as lucky
```

**Comment by tadashi-aikawa** [comment]
@lguenth 
Released in [v7.2.2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.2.2) 🚀 

Please confirm it 🙏

**Comment by lguenth** [comment]
@tadashi-aikawa Yessss, it works again! Thanks so much! 🎉🚀

You know what, it's really weird but I noticed the same issue in two other plugins, `Zotero Integration` and `Open with` and told the devs. But I didn't have the chance to look into your code. I'm glad you found it yourself!

**Comment by tadashi-aikawa** [comment]
Thank you for your confirming 👍

**Comment by tkern** [comment]
hi @tadashi-aikawa i am running into the exact same issue and i have (for the first time) installed the plugin yesterday.
i have version 8.9.1 on macosx. rg was installed with homebrew and i set the path to it in the config to: `/usr/local/bin/rg`.

obsidian has full disk access. any ideas what is wrong?

**Comment by tadashi-aikawa** [comment]
Sorry for my late answer, @tkern :)

Just to confirm, can you execute the `/usr/local/bin/rg` command in the terminal?

**Comment by tkern** [comment]
No worries, thanks for the reply.

yes i can:

```
/usr/local/bin/rg
error: The following required arguments were not provided:
    <PATTERN>

USAGE:

    rg [OPTIONS] PATTERN [PATH ...]
    rg [OPTIONS] -e PATTERN ... [PATH ...]
    rg [OPTIONS] -f PATTERNFILE ... [PATH ...]
    rg [OPTIONS] --files [PATH ...]
    rg [OPTIONS] --type-list
    command | rg [OPTIONS] PATTERN
    rg [OPTIONS] --help
    rg [OPTIONS] --version

For more information try --help
```

**Comment by tadashi-aikawa** [comment]
@tkern 
Thanks!

If it runs correctly, it sholud show the count of results as follows.

![image](https://user-images.githubusercontent.com/9500018/233775185-bbcc3eb1-19ca-4cc8-af8d-1470f762530d.png)

Didn't you show that?

**Comment by tkern** [comment]
it does not show anything.
![CleanShot 2023-04-23 at 12 16 17](https://user-images.githubusercontent.com/7567280/233833980-544a9c2b-16fd-450f-bfd4-8d6bff50b454.jpg)
![CleanShot 2023-04-23 at 12 16 08](https://user-images.githubusercontent.com/7567280/233833984-2c834c23-a3f2-4aee-ab95-0eb756c07cf1.jpg)

**Comment by tadashi-aikawa** [comment]
@tkern 
Did you push a "TAB" key?

**Comment by tkern** [comment]
@tadashi-aikawa oh boy, this is embarrassing. i thought you are searching with every keystroke automatically :/ i can see search results after pressing <TAB>
