### ISSUE TITLE
Show front matter

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-another-quick-switcher#122]
![image](https://user-images.githubusercontent.com/9500018/201507349-a5491e92-5c23-445a-9202-a061aeeeff63.png)

**Comment by tadashi-aikawa** [comment]
![image](https://user-images.githubusercontent.com/9500018/201509873-e7d33335-3a31-410f-8a11-a465bcb58fcc.png)

**Comment by tadashi-aikawa** [comment]
It can't search by front matter as far, only show them.

**Comment by tadashi-aikawa** [comment]
Released in [v7.3.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.3.0) 🚀

**Comment by FelipeRearden** [comment]
Fantastic idea @tadashi-aikawa  !!!!!

### 💡Idea

Would be possible to have a field to define some frontmatter keys to be excluded from the AQS modal 

I have some keys that I would like to be excluded (they are structural keys and not informative keys):
⦿ css class
⦿ url -> I have this key with the url of the article in my DB app that I use to run a Templater script to open the article in the DB app from Obsidian
⦿ Number-headings -> key from a plugin that I use to add number to the headings of a note
⦿ obsidianUIMode & obsidianEditingMode -> keys from a plug-in that I use to force the view of specifics notes 

![63CC9DAF-9327-4417-8B61-0FF206266114](https://user-images.githubusercontent.com/85180696/201515791-2c41bb75-c731-4b0d-87af-824a520a2b82.jpeg)


Let me know what you think :)

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Cool! I'll add the feature in the next release 👍

**Comment by FelipeRearden** [comment]
> @FelipeRearden
> Cool! I'll add the feature in the next release 👍

Amazing 💙💙💙

Thank you very much @tadashi-aikawa !!!!!!!!!!!!!!

**Comment by tadashi-aikawa** [comment]
Released in [v7.4.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.4.0) 🚀
