### ISSUE TITLE
Add a "Exclude keys of front matters" option

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-another-quick-switcher#123]
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/122#issuecomment-1312689031

**Comment by tadashi-aikawa** [comment]
Fixed in [v7.4.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.4.0) 🚀

**Comment by FelipeRearden** [comment]
> Released in [v7.4.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.4.0) 🚀 

Working perfect on version v7.4.0 on Obsidian Mobile [iPadOS] v1.4.1

Thank you very much @tadashi-aikawa !!!!!!

This new feature has a huge impact on my notes.

 I am starting to using obsidian as a Database and using YAML to store information for Specific Notes.

AQS is gonna be able to let me search for this notes and easily see this information that is located in the YAML easily
→ AQS is getting a new super power :) 


> Add a "title" attribute to the front matter span

Fantastic idea !!!!!! 

---

P.S. I am starting to migrate my environment from v15.9 to v1.x on Mobile. BUT I already can say that **AQS** and **VC** are **spectacular** on Mobile @tadashi-aikawa . Both look 100% equal on Mobile and Desktop. 

Have a great day !!!!
