### ISSUE TITLE
[Feature Request] Switching Between Header Search in File → Header **Floating** Search in File

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#124]
Hello @tadashi-aikawa !!!!!

My FR is related to the commands `Header Search in File` and `Header Floating Search in File`

My FR is simple to explain: would be amazing to have a hotkey inside the `Header Search in File`  that let the user **switch** to the  `Header Floating Search in File` modal

I know that sounds crazy, but let me explain in practice with a real world example...

### My Workflow

I have books notes that has a lot of headings. I really like to organize my notes is headings because its easy for me to isolate content 

My workflow to revisit old content for research can be divided into 2 steps:

1️⃣ Take a look at all TOC (headings) → `Header Search Modal`

2️⃣ Select a Chapter that resonates with me → `Header Search Modal`

3️⃣ **Do a quick look at the content of the Items inside the chapter** → `Header Floating Search Modal`

4️⃣ Reading the content of the chosen item → `Hit Enter in Header Floating Search Modal`

## My Idea 

Evoke `Header Floating Search Modal` from the `Header Search Modal` with a modal hotkey

![A5EAFAE7-366A-4BD4-BF6D-F66C5B569C45](https://user-images.githubusercontent.com/85180696/201740962-8a163c24-a977-4321-ad91-12364dcb50cc.jpeg)

📽 Like this :)

https://user-images.githubusercontent.com/85180696/201741032-64438593-61b9-429a-867d-5d6ee53c9110.MOV

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
Hi, @FelipeRearden :)

Could you tell me why you didn't use only `Header Floating Search Modal`? I think it should satisfy your requirements. (In my case, I only use `Header Floating Search Modal`)

**Comment by FelipeRearden** [comment]
> Hi, @FelipeRearden :)
> 
> 
> 
> Could you tell me why you didn't use only `Header Floating Search Modal`? I think it should satisfy your requirements. (In my case, I only use `Header Floating Search Modal`)

Let me try to explain why I need this feature.

Three main points of my workflow:

1️⃣I process a lot of books inside obsidian. This way I have notes with more than 3000 lines and many many many h3,h4 and h5

2️⃣ I use a lot of custom html tags and callouts to decorate my notes. This way Live Preview is a bit laggy when scrolling between these large notes.

3️⃣ lack of available keyboard hotkey. I almost don’t have more slots available. Every new workflow that I created it’s a nightmare to find a way to incorporate in a new hotkey

This way, using Header Search in File as my main heading search engine is perfect for me because I can select chapters from these notes in a fast way 

Header Floating Search is only triggered when I already selected a main header to take a deep look and finally selecting that exact H4 or H5 that I want to read/write.

---

I completely understand that is a unconventional workflow. I have a tendency to always try to automate my workflows (specially when it’s operations that I do many many times everyday like the ones I do on AQS and VC)

Let me know what you think :)

**Comment by tadashi-aikawa** [comment]
Thank you for your explanation :)

> This way Live Preview is a bit laggy when scrolling between these large notes.

Does your problem is that AQS shows a preview immediately? If so, the delay settings will be another solution. What do you think?

**Comment by FelipeRearden** [comment]
Thank you very much for your help with this issue :)

> Does your problem is that AQS shows a preview immediately? If so, the delay settings will be another solution. What do you think?

In my humble opinion. we dont need a delay settings. `Header Floating` is working perfect the way that is working now. 

The lagging issue is 100% related to my environment (huge notes and an old device 🥲). 

My real pain point for this FR is the need to have two hotkeys shortcuts to switch between `Header Search` and `Header Floating Search` because I feel more comfortable using `Header Search` as my main header modal for all notes and `Header Floating Search` only for these specific notes that have 50+ headers. 

Feel absolutely free to close this issue if you feel is very specific :)

Thank you very for everything @tadashi-aikawa !!!!!!

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Released in [v8.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.1.0) 🚀

**Comment by FelipeRearden** [comment]
> Released in [v8.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.1.0) 🚀

Hello @tadashi-aikawa !!!!!!

This is absolutely fantastic !!!! Thank you very much :)

Working perfect Mobile on version 1.4.1 on iPadOS

What a great way to start a new year !!!! Thank you very much @tadashi-aikawa you are a legend 🥇
