### ISSUE TITLE
FR: Improved exclude or a guide on how to use the ignore patterns?

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-another-quick-switcher#13]
This feature request is on how to exclude certain folders from the AQS. I would like to excluse a whole folder fo the switcher, but I don't know what sort of regexp pattern to use.

alternatively, it would be great if you could steal some of the code from zootelkeeper or another plugin that allows the user to pick folders to include or exclude, like so:

![image](https://user-images.githubusercontent.com/49103046/144145466-e968572e-2503-43e3-a9c2-79cc62d39ff2.png)

In lieu of that it would be good to have a guide on how to do this—I didn't see one when I looked around the repo, so apologies if i missed it!

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats.

> but I don't know what sort of regexp pattern to use.

- If you want to ignore a `AAA` directory, set `AAA/`
- If you want to ignore `AAA` and `BBB` directories, set `(AAA|BBB)/`

I think the options are difficult for users to understand because I created them temporarily. However, I'd like to try to improve it because there are users who use it as you do :)

**Comment by brimwats** [comment]
thanks for the help! I will try it out and see if I can get it working—also happy to test out enhancements :)

**Comment by brimwats** [comment]
followup on this: if you don't know regex it gets really hard with a foldername like `booxsidian\400 - Society. Philosophy. Psychology. Religion\15. Productivity & Psychology\3. Psychology` 

it would also be nice to exclude certain things like a folder of root words I have:

![image](https://user-images.githubusercontent.com/49103046/146128805-ffc152c0-b63d-4a3a-b9d4-0b52b9eea8fa.png)

**Comment by tadashi-aikawa** [comment]
@brimwats 
Ah.. That is very difficult.. 😇  I suppose to implement **prefix path filter**.

**Comment by brimwats** [comment]
love that idea! thanks for considering it

**Comment by tadashi-aikawa** [comment]
@brimwats 
I have released to [v3.3.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/3.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by brimwats** [comment]
works! thanks for all your labor!
