### ISSUE TITLE
FR: Normalise accents/diacritics should also normalise ²/³/superscript numbers

### ISSUE THREAD

**Issue by Gewerd-Strauss** [tadashi-aikawa/obsidian-another-quick-switcher#131]
Hello,

the diacrititc- and accent-normalisation is a really great feature when searching through a super-doc with 120+ headings. However, I'd suggest that superscript or subscript strings should be normalised for searching as well - that includes the default ²/³ commonly found on keyboards, and the same for other numbers (as there are a variety of cases where that can be viable, and various keyboards capable of actually sending those symbols.

Thank you.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.

**Comment by Gewerd-Strauss** [comment]
I am terribly sorry for vanishing on this. I have been first busy with family crap over christmas and NYE, and have been focussing on my upcoming exams since then. And thus, this unfortunately fell through my cracks and down my tracker into obscurity.

---

I made some test runs, and most diacritics I have access to do work. However, neither of the standard numbers, or generally any sub/sup-tagged text is parsed:
    
    # A1 **
    # A2 **
    # A² /
    # B³ /
    # å **
    # B<sup>3</sup><sub>4</sub> **
    
The middle two, marked with "/", cannot be found when searching for their numbers.
---


Again, I'm sorry.
Sincerely,
~Gw


---
P.S.:
I made the curious discoveries that 
- unicode does not work either, but that is unreasonable to assume, and most likely way too much to even attempt to implement, 
- and latex works, which makes sense, considering it is just plaintext under the hood

This means that _technically_ one could get away with writing all super-/subscript numbers via latex, but that is kind of really exhaustive :P

**Comment by tadashi-aikawa** [comment]
Thank you for coming back for me, @Gewerd-Strauss  :)

OK. I will support the following cases.

- A² (hit by 2)
- B³ (hit by 3)

If I misread your comment, please tell me what is wrong.

**Comment by Gewerd-Strauss** [comment]
> If I misread your comment, please tell me what is wrong.

No you did not, that is exactly what I am looking for.

Thank you.

**Comment by tadashi-aikawa** [comment]
@Gewerd-Strauss 
Released in [8.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.5.0) 🚀
