### ISSUE TITLE
FR: Support opening .canvas files

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#133]
I am quite surprised that there hasn't been a feature request for this yet. Right now, we have to use the core plugin quick switcher if we want to open a canvas file, which is quite annoying.

**Comment by tadashi-aikawa** [comment]
Probably, It will be implemented as the issue, https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/21.

**Comment by kometenstaub** [comment]
I would also appreciate this :)

**Comment by tadashi-aikawa** [comment]
I understand that is an unsafe implementation (using not public APIs). But if some people want to use the AQS in the canvas... :trollface: ( `insert to editor` or `insert all to editor` )

https://user-images.githubusercontent.com/9500018/209671998-5b63a9e6-74f0-492c-a1b4-c226db51d524.mp4

**Comment by tadashi-aikawa** [comment]
Released in [v8.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.0.0-beta2) 🚀 

https://user-images.githubusercontent.com/9500018/209675872-c139f8f7-85e9-4734-9cdc-88f120388abe.mp4

**Comment by tadashi-aikawa** [comment]
Released in [v8.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.0.0) 🚀
