### ISSUE TITLE
[FR] Shortcut to preview and focus the newly opened file

### ISSUE THREAD

**Issue by Glint-Eye** [tadashi-aikawa/obsidian-another-quick-switcher#136]
Hello :)

It would be great if there was another shortcut, that could preview a selected file and at the same time focus on the newly opened file and update the context for the search modal. This would be especially helpful when you use Another Quick switcher to navigate backlinks and outlinks. Previewing a selection would automatically open up the backlinks / outlinks for the next file to quickly navigate through your vault. Additionally for this use case it would be great if Another Quick Switcher could pass through the native "navigate forward" and "navigate back" commands and update the modal accordingly.

Cheers :)

**Comment by tadashi-aikawa** [comment]
Hi, @Glint-Eye :)

There should be a luck of features (ex: Show outgoing link from the dialog), but I think it's similar to "Show backlinks from the dialog (https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/44)" released in [v7.7.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.7.0).

What do you think?

**Comment by Glint-Eye** [comment]
Ah yes. the "show backlinks from the dialog" option actually works better I would say. Previewing this way could stay optional, which I'd actually prefer. Then I'd just suggest to add a "show outlinks from dialog" command :)

**Comment by tadashi-aikawa** [comment]
> I'd just suggest to add a "show outlinks from dialog" command :)

OK. I'll implement it 👍

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
Works perfectly?

https://user-images.githubusercontent.com/9500018/210304477-ee956c69-a8f0-473a-b465-311099b2afdd.mp4

**Comment by Glint-Eye** [comment]
> @Glint-Eye Works perfectly?
> 2023-01-03_14h31_14.mp4

This looks really good. Especially the implementation of navigate back and forward makes perfect sense. This should make navigating through your vault via outlinks and backlinks super easy.

Thx a lot :)

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
Thanks for your confirming!

I'll release this feature soon 👍

**Comment by Glint-Eye** [comment]
Just tried it out. Works very well. But it would be great if the sort priorities could also support sorting by "order of appearance in a file" when navigating through outlinks with "Ctrl + L". The same way a dedicated Outlink search works when no priorities are set.

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
Thanks for your feedback! Right. I will implement options that enable us to select a custom search we set 👍

**Comment by tadashi-aikawa** [comment]
Release id [v8.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.2.0) 🚀 

Let me close this issue. (If you want, we should trace the unfinished task in another issue)

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 

> Just tried it out. Works very well. But it would be great if the sort priorities could also support sorting by "order of appearance in a file" when navigating through outlinks with "Ctrl + L".

Released in [v8.2.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.2.1) 🚀  (It's my mistaken..)
