### ISSUE TITLE
[FR] Option to always open other extensions in default Application

### ISSUE THREAD

**Issue by Glint-Eye** [tadashi-aikawa/obsidian-another-quick-switcher#137]
Now that multiple file formats are supported, it would be nice if there was an option in settings to always open in default application (except for obsidian native extensions like .canvas .excalidraw and .md i suppose). I pretty much never want to open files like PDFs or images inside of obsidian but rather just reference to them.

Or alternatively a text box in settings to define which extensions should be opened in the default application

**Comment by tadashi-aikawa** [comment]
Hi, @Glint-Eye :)

OK. 👍

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
By the way, what do you think about adding an "open in default" command?

**Comment by Glint-Eye** [comment]
> @Glint-Eye By the way, what do you think about adding an "open in default" command?

yes that would work too :)
