### ISSUE TITLE
Feature request: limit to existing files only

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-another-quick-switcher#14]
I keep accidentally creating new files when I actually just want to go to existing ones. I think the default switcher has a limit option so it would be nice here too!

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats. Thank you for your Feature request!

Do you mean you don't want to create a new file even if `Shift + Enter,` right?

**Comment by brimwats** [comment]
right—but more a toggle or something similar so that's not even an option (i.e. it just offers existing items). 

or maybe a visualization if the file isn't created? like, text in red or something? I don't know what's easier, codewise! I will ask in the CSS discord channel too!

**Comment by tadashi-aikawa** [comment]
> I keep accidentally creating new files when I just want to go to existing ones.

Could it be that you don't want to create a new file colored gray as follows?

![image](https://user-images.githubusercontent.com/9500018/145914306-e5f9035e-c5fc-42dd-8a71-2c5a0dfc7641.png)

They are included in files as internal links, but It doesn't create as a file.

**Comment by brimwats** [comment]
That could help! any tips stylizing it because it doesn't stand out as much for me 

as you can see:
![image](https://user-images.githubusercontent.com/49103046/146128531-c64d60ef-4a65-455c-986b-9c23fd91caf8.png)

**Comment by tadashi-aikawa** [comment]
> limit to existing files only #14

LGTM! I'll implement it 👍 

Until release, you can set in your CSS as follows.

```
.another-quick-switcher__phantom_item {
    color: your-favorite-color
}
```

The default is `var(--text-faint)` that depends on the theme you use.

**Comment by brimwats** [comment]
thank you so much for your help!! I'll try it or tomorrow 😃

**Comment by tadashi-aikawa** [comment]
@brimwats 
I have released to [v3.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/3.0.0) 🚀

Please confirm whether it works as you expected.

**Comment by brimwats** [comment]
thanks so much!! I can try it out tomorrow! 😀

**Comment by brimwats** [comment]
it works! thanks so much :)
