### ISSUE TITLE
FR: Option to change size of the switcher modal 

### ISSUE THREAD

**Issue by ArtemisFowl-san** [tadashi-aikawa/obsidian-another-quick-switcher#141]
Basically, the title. I couldn't find a feature request for this.

**Comment by tadashi-aikawa** [comment]
Thanks for your FR, @ArtemisFowl-san :)

However, I am not going to add the feature for now. For details, please see https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/129#discussioncomment-4437281.

Best regards.

**Comment by ArtemisFowl-san** [comment]
Thanks for the quick reply. I understand your objection to this. 

Thanks for making such a cool plug in :)
