### ISSUE TITLE
Feature request: Key binding for `dismiss` (e.g. Ctrl-[ or Ctrl-c)

### ISSUE THREAD

**Issue by shitcoding** [tadashi-aikawa/obsidian-another-quick-switcher#143]
First of all, thank you for this amazing plugin! I'm really enjoying using it and it's enhanced my Vim-mode Obsidian workflow a lot!

Anyway, my question is: is it possible to implement a keybinding for "dismiss"? Currently, it's bound to [Esc], but I've tried to find a way to bind it to Ctrl-C or Ctrl-[ to match Vim bindings. I searched the issues and read the readme but was unsuccessful.

If it's possible, that would be great.
Thanks in advance!

**Comment by tadashi-aikawa** [comment]
Hi, @shitcoding :)  I'm glad to hear that this plugin enhances your Vim-mode experience.

> is it possible to implement a keybinding for "dismiss"?

It would be possible. I'll release it in the next release 👍

**Comment by tadashi-aikawa** [comment]
@shitcoding 
Released in [8.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.5.0) 🚀

**Comment by shitcoding** [comment]
YEAAAAH this is so awesome
Thank you so much! You're the best!
