### ISSUE TITLE
Doesn't move the cursor at the end of the link when inserting into editor

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#145]
When inserting a link into the editor via shortcut, the cursor remains at the beginning of the link whereas it would make more sense to have it at the end in order to continue writing.

**Comment by tadashi-aikawa** [comment]
Hi, @tim-hilde :)

I agree with you. However, at that time, I didn't implement it that way because some problems prevented me from doing so.

I'll try it again as possible as I can👍

**Comment by tim-hilde** [comment]
In addition to that, it would be nice to have the option to insert the link in background so that the modal of AQS is still present

**Comment by tadashi-aikawa** [comment]
Right. Additionally, inserting a line break after the insertion link in the background looks better.

**Comment by tadashi-aikawa** [comment]
@tim-hilde 
Released in [v8.6.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.6.0) 🚀
