### ISSUE TITLE
FR: hide individual hotkey guides

### ISSUE THREAD

**Issue by ggstrader** [tadashi-aikawa/obsidian-another-quick-switcher#148]
We've got a setting already for hiding all hotkey guides, but it'd be nice to be able to determine which are hidden. Some are useful, many just add clutter.

**Comment by tadashi-aikawa** [comment]
Hi, @ggstrader :)

Right. I'll add options near hotkey settings 👍 

![image](https://user-images.githubusercontent.com/9500018/223429059-4f207e75-3c94-4962-9eaf-ce0361e25872.png)

**Comment by tadashi-aikawa** [comment]
@ggstrader 
Released in [v8.7.0-beta1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.7.0-beta1) 🚀 

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. 

![image](https://user-images.githubusercontent.com/9500018/224550898-fa6950cc-213d-4dab-ab8c-3758228775d1.png)

**Comment by tadashi-aikawa** [comment]
@ggstrader 
Released in [v8.7.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.7.0) 🚀

**Comment by tim-hilde** [comment]
Please add the option to hide "[up]", "[down]" and "open Nth", too 

<img width="261" alt="image" src="https://user-images.githubusercontent.com/44113468/226205242-55fd66ae-e606-46f6-9f69-59650a271113.png">
