### ISSUE TITLE
Feature request: Show more suggestions in the search result list

### ISSUE THREAD

**Issue by avirosso** [tadashi-aikawa/obsidian-another-quick-switcher#15]
First: This plugin is great! Thanks!

But: Currently the 'normal / tag search' and the 'recent search' shows only a maximum of 10 suggestions / search results. This a an annoying restriction (especially when searching tags).

It would be great, if the search result lists shows more/all (preferably a custumizable number of) suggestions (resulting in a scrollable result list like in the 'backlink search').

**Comment by tadashi-aikawa** [comment]
Hi, @avirosso. Thank you for your FR!

I agree with you, so I'll implement it 👍

**Comment by tadashi-aikawa** [comment]
@avirosso 
I have released to [v3.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/3.1.0) 🚀

Please confirm whether it works as you expected.

**Comment by avirosso** [comment]
Yes, works great (and even custumizable)! Thanks!
