### ISSUE TITLE
FR: regex exclusions and option to include files

### ISSUE THREAD

**Issue by ggstrader** [tadashi-aikawa/obsidian-another-quick-switcher#150]
Right now exclusions only work on folders, and only match prefixes. It'd be nice to have the option to exclude files as well, and to use regex for each of the matchers.

Another note is that AQS doesn't seem to respect Obsidian's built-in file exclusion, maybe that's something to consider allowing as well?

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
