### ISSUE TITLE
"Link search" and "Backlink search" cannot display aliases.

### ISSUE THREAD

**Issue by github-lxf** [tadashi-aikawa/obsidian-another-quick-switcher#154]
Thank you for your plugin, it has made it more convenient for me to see the aliases. Because my markdown files are named with numbers, I use aliases to organize them. However, the aliases cannot be displayed in Link search and Backlink search. Is it possible to make them display the aliases as well? Thank you again.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @github-lxf :)

Right. I'll try to implement it 👍

**Comment by tadashi-aikawa** [comment]
If the word hits an alias, they are displayed. The behavior is the same as not "Link search" and "Backlink search"🤔 

![image](https://user-images.githubusercontent.com/9500018/224524211-1431584c-a9a7-4778-89de-22ddd9210b1b.png)

**Comment by github-lxf** [comment]
I have found the reason - it was due to my incorrect settings. I am sorry for any trouble caused.
