### ISSUE TITLE
Bug: It creates a new tab on a pinned note.

### ISSUE THREAD

**Issue by alanlee127** [tadashi-aikawa/obsidian-another-quick-switcher#157]
When I open the plugin on a pinned note, it creates a new tab. Once I press esc to cancel the search, the focus automatically jumps to the new tab. 
It's not a big issue, but may affect the experience a bit.

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @alanlee :)

I could reproduce it. I have never used the `pinned` feature and never noticed it. I'll attempt to fix it as possible as I can :+1:

**Comment by tadashi-aikawa** [comment]
Mmm... This is an effect of a tricky implementation to achieve the preview functionality and is difficult to fix.😢 Let me remain this issue open.

**Comment by kometenstaub** [comment]
This also happens when the switcher is opened in a Style Settings tab. 
I don't know where the underlying issue is. Does the picture I sent give you any idea at all? If `canNavigate()` is false, choose a different behaviour for example?

<img width="351" alt="image" src="https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/83140328/fc16ccc2-5578-4245-b685-89ee2e3c3b56">

**Comment by kometenstaub** [comment]
Btw, it opens two panes when I open the quick switcher and one when I close it.

The issue for closing might lie here:

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/blob/94d793cc4a544e0b1a1ed0e2483984262487a622/src/ui/AnotherQuickSwitcherModal.ts#L200

Instead, you should probably use `this.app.workspace.getActiveViewOfType(View)`.

The two that are created on opening of the modal are probably here: 

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/blob/94d793cc4a544e0b1a1ed0e2483984262487a622/src/ui/AnotherQuickSwitcherModal.ts#L120

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/blob/94d793cc4a544e0b1a1ed0e2483984262487a622/src/ui/AnotherQuickSwitcherModal.ts#L125

**Comment by tadashi-aikawa** [comment]
@kometenstaub 
Thank you for your advice and the PR :) This time, the issue was resolved thanks to Pjeby's pull request, but I still appreciate your cooperation👍

**Comment by tadashi-aikawa** [comment]
@alanlee127 @kometenstaub 
Released in [v8.10.0-beta5](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0-beta5) 🚀

I should be able to release the stable version this weekend 👍

**Comment by tadashi-aikawa** [comment]
Released in [v8.10.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0) 🚀
