### ISSUE TITLE
One of my markdown files not appearing in results

### ISSUE THREAD

**Issue by csss1234** [tadashi-aikawa/obsidian-another-quick-switcher#158]
- Appears in Obsidian quick switcher, appears in obsidian backlinks pane etc
- Neighboring .md files in same folder appear in results
- Made a duplicate of the file, duplicate appears in results.
- No special characters in name. Tried renaming. Still doesn't appear
- Also fails to find this .md on mobile

I have very few search criteria. 
![SCR-20230329-oevd](https://user-images.githubusercontent.com/45954264/228655056-f10029d7-01c6-486e-a81d-96136f6ff717.png)

Looks a lot like most of my notes, nothing special. Not a massive vault, maybe 1000 md files, 5gb. 

And as I finish making this bug report... it starts appearing again.

**Comment by tadashi-aikawa** [comment]
Hi, @csss1234 :)

Another Quick Switcher generates indexes upon startup, taking a few seconds depending on the device's specifications. Does this issue only occur immediately after startup?

**Comment by csss1234** [comment]
No, the app had been running for maybe an hour, and when I discovered this problem, I messed with it for at least 5 mins before it started working.

**Comment by tadashi-aikawa** [comment]
@csss1234 
Thannk for your reply :)

Hmm... It looks strange. Please inform me of the reproduction procedure if you can reproduce it in the sandbox vault. Otherwise, it is not easy to fix it because I need to figure out why and how the issue occurs.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
