### ISSUE TITLE
Feature Request: Use ctrl+j/ctrl+k to scroll through files

### ISSUE THREAD

**Issue by Aaron-Bopp** [tadashi-aikawa/obsidian-another-quick-switcher#16]
After using this in Various complements, I opened up the quick switcher and my muscle memory took me to those keys. Would appreciate it here as well :D

**Comment by tadashi-aikawa** [comment]
@Aaron-Bopp 
I have released to [v3.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/3.2.0) 🚀

Please confirm whether it works as you expected.

**Comment by Aaron-Bopp** [comment]
It does indeed! Thank you very much

**Comment by jzhang-brex** [comment]
Consider add this to README

**Comment by tadashi-aikawa** [comment]
Same as https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/12#issuecomment-1026355240
