### ISSUE TITLE
Changed settings don’t save 

### ISSUE THREAD

**Issue by csss1234** [tadashi-aikawa/obsidian-another-quick-switcher#161]
When I add an excluded folder path, and change no other setting, it doesn’t stick. Quit obsidian, and it’s back to original. Have to toggle one of the sliders to get it to update the settings file.

**Comment by tadashi-aikawa** [comment]
Hi, @csss1234 :)

Please check the sentence in the README 👍 
![image](https://user-images.githubusercontent.com/9500018/232026701-e91f9237-1955-4bbe-b178-de4b1bec1c5a.png)

If possible, I think I want to improve this specification because it's not intuitive.
