### ISSUE TITLE
[Feature Request] Header Floating Search infile → Different Positions Based on Left/Right Split

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#164]
Hello @tadashi-aikawa !!!!!

I would like to share with you an idea about the position of the AQS modal **Header Floating Search infile**

In Obsidian we have 2 windows:

1️⃣ **Single Open Window**
![AA7A904F-9B1B-41CA-BFF3-ABADC76F20B3](https://user-images.githubusercontent.com/85180696/234283490-730afb81-38f4-4f2a-9cf7-c9d5ca1939eb.jpeg)

2️⃣ **Two Open Windows: Left and Right**
![B4A76222-817A-4EA8-9802-91B6E0609394](https://user-images.githubusercontent.com/85180696/234283784-3aac1c05-2f9f-4ea5-ac75-979db6b0a141.jpeg)

## MY FR

**ONLY** when we have Two Open Windows I would like to be able to have a different position for the **Header Floating Search** based on the position of the Active Note:

I am thinking about something like this...

📸 Active Note is in the Left
![0606F8D0-91EA-4332-96DD-DDB3AF9D7B1F](https://user-images.githubusercontent.com/85180696/234284135-fa6575da-8873-4508-ac13-25a85a9c26b2.jpeg)

```css
.prompt.another-quick-switcher__floating-prompt {
 	left: 920px !important;
}
```

📸 Active Note is in the Right
![63313597-91DC-42FB-929F-CBAC18EEAB7D](https://user-images.githubusercontent.com/85180696/234283955-b63acf87-841e-4c5a-841c-2adfb04d58a3.jpeg)

```css
.prompt.another-quick-switcher__floating-prompt {
 	left: 20px !important;
}
```

This way, we could have a clear vision of the note while cycle through the headers.

🙏 If possible, would be amazing if this setup is in style.css this way power css users could adjust the position based on their themes :)

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @FelipeRearden :)

Sorry, I think it is too difficult to implement it. Additionally, we can show/edit multiple notes using tabs, even if only one window exists.

Best regards.
