### ISSUE TITLE
BUG：After updating Obsidian to version 1.2.6, the search function cannot be launched. 

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-another-quick-switcher#165]
After updating Obsidian to version 1.2.6, the search function cannot be launched. Pressing the shortcut key does not open the search window as usual. This is the error log.
[obsidian.md-1682544692711.log](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/files/11337449/obsidian.md-1682544692711.log)

Best regards.

**Comment by kmaustral** [comment]
Confirmed

**Comment by Comprehensive-Jason** [comment]
Having the same issue.

**Comment by emisjerry** [comment]
Starred plugin removed made this problem.

![image](https://user-images.githubusercontent.com/131511/234733705-fc42bd0d-823e-45e9-a838-8eedfcca9138.png)
![image](https://user-images.githubusercontent.com/131511/234733716-6c4d11b8-86de-44eb-996f-8ec3a4f51b06.png)

**Comment by tadashi-aikawa** [comment]
Thanks, everyone!

I'll fix the issue as soon as I can. (But I am working now in the office 😓 )

**Comment by tadashi-aikawa** [comment]
Fixed in 8.9.2 🚑 

The version treats bookmarks as star files. I want to support bookmarks officially later. (Maybe v9.0.0)
