### ISSUE TITLE
open in explorer command from search view

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-another-quick-switcher#168]
### Discussed in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/153

<div type='discussions-op-text'>

<sup>Originally posted by **danielbsweeney** March 10, 2023</sup>
hi,

great plugin.

just wondering if there would be a chance we could have a open in explorer command when searched. open in default app is there but i don't believe there is a way to open in explorer.

cheers</div>

**Comment by tadashi-aikawa** [comment]
Fix in [v8.11.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.11.0) 🚀

**Comment by danielbsweeney** [comment]
ace!

thanks


Daniel Sweeney
3D Generalist

*Mobile:* +44 (0)7743429771
*Email:* ***@***.*** ***@***.***>
<http://northforge.co.uk/>


*Sent with Shift
<https://tryshift.com/?utm_source=SentWithShift&utm_campaign=Sent+with+Shift+Signature&utm_medium=Email+Signature&utm_content=General+Email+Group>*
