### ISSUE TITLE
Sort by last accessed is limited to 10 most recent files

### ISSUE THREAD

**Issue by scpedicini** [tadashi-aikawa/obsidian-another-quick-switcher#17]
Another quick switcher lets you increase suggestion list using: "Max number of suggestions", for example, mine is currently set to 25 suggestions. However, when you first open "Another Quick Switcher", it only sorts the first 10 by most recently accessed which is the behavior of the official Quick Switcher, but the last 15 are unsorted notes.

**Comment by tadashi-aikawa** [comment]
Hi, @scpedicini. Thank you for your bug report :)

I could reproduce it 👍

**Comment by tadashi-aikawa** [comment]
@scpedicini 
I have released to [v4.0.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.0.1) 🚀

Please confirm whether it works as you expected.

**Comment by scpedicini** [comment]
@tadashi-aikawa Just tested it out, works fantastic! Thanks so much - this plugin makes Obsidian so much better.
