### ISSUE TITLE
Extra tabs created

### ISSUE THREAD

**Issue by kmaustral** [tadashi-aikawa/obsidian-another-quick-switcher#170]
I'm using 8.10 beta with 1.30 Obsidian. 

When I open a note with one already pinned in the window, it creates three empty tabs as well as opening the note.

**Comment by tadashi-aikawa** [comment]
Thank you for your bug report, @kmaustral :)

Duplicated with https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/157.
