### ISSUE TITLE
Bug: Current tab history is corrupted when switcher closes

### ISSUE THREAD

**Issue by pjeby** [tadashi-aikawa/obsidian-another-quick-switcher#171]
Steps to reproduce (on Obsidian 1.2.8):

1. Open a series of documents in a tab by navigating links (either between notes or using folder pane, bookmarks, etc.)
2. Drop down the back history list to see how many items there are and in what order
3. Open a switcher
4. Close it
5. Drop down the back history list again -- items are missing from the list that was seen in step 2

If you actually open a file, it does the same thing - the item before the note open in step 1 is removed from the tab's history.

**Comment by pjeby** [comment]
The grep dialog has the same issue, by the way; I've now submitted PR #172 to fix both dialogs.

**Comment by tadashi-aikawa** [comment]
Hi, @pjeby :)

Thank you for your kind Issue and PR. I will check it out as soon as possible 👍

**Comment by tadashi-aikawa** [comment]
Released in [v8.10.0-beta5](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0-beta5) 🚀 

I should be able to release the stable version this weekend 👍

**Comment by tadashi-aikawa** [comment]
Released in [v8.10.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.0) 🚀
