### ISSUE TITLE
cant exclude any folder named `assets` in setting... is this a bug 

### ISSUE THREAD

**Issue by zeltak** [tadashi-aikawa/obsidian-another-quick-switcher#174]
hi 

hi have subfolder in many dirs names `assets` where I store my images

I want the to be excluded in the recommended search 

I tried this

![CleanShot 2023-05-19 at 13 17 58](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/498410/d05ac844-fa17-466f-ba52-b457798b151f)

ie using regex to match on `^assets`

but that seems not to work

any clue what im doing wrong?

Z

**Comment by tadashi-aikawa** [comment]
Hi, @zeltak :)

"Exclude prefix path pattern" doesn't support the regex patterns.  Please see the details below.

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/13

**Comment by tadashi-aikawa** [comment]
If you want to ignore assets, please consider filtering by file extensions.

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/8214ca6b-d25c-4ad1-9ac1-09829b493734)

**Comment by zeltak** [comment]
ahh got it thx so much!!
