### ISSUE TITLE
Move through link/backlink instances while in preview

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#177]
When showing links or backlinks in a file it'd be great to preview all occurrences of said links. Currently only the first (?) instance is shown.

**Comment by tadashi-aikawa** [comment]
Hi, @tim-hilde :)

We currently have no plans to add such a feature to the Custom search due to its challenging implementation.

However, I have been considering creating a rich backlink search command separately from the Custom search, similar to the Header search.

**Comment by tadashi-aikawa** [comment]
> However, I have been considering creating a rich backlink search command separately from the Custom search, similar to the Header search.

Released in [v9.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/195) 🚀

**Comment by tadashi-aikawa** [comment]
@tim-hilde 
Released in [v9.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/9.0.0-beta2) 🚀
