### ISSUE TITLE
Closing preview closes open tab

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#178]
Say I have two tab groups and I now want to show the backlinks of the right one. When I now preview one of the links and close the preview the tab is closed whereas I would expect to go back to the original one

**Comment by tadashi-aikawa** [comment]
Hi, @tim-hilde :)

Does it occur in the latest version? (Obsidian v1.3.4 & Another Quick Switcher v8.10.0)

**Comment by tim-hilde** [comment]
Yes it does:

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/44113468/492844e5-a887-414a-809a-3a34b792a0b0

**Comment by tadashi-aikawa** [comment]
@tim-hilde 
Thanks! I could reproduce it 👍

I feel like the latest update for Obsidian has broken it.

**Comment by tadashi-aikawa** [comment]
@tim-hilde 
Fixed in [v8.10.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.10.1) 🚀
