### ISSUE TITLE
[Feature Request] Using Text Selected in the Active Note in the AQS Modal

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#179]
Hello @tadashi-aikawa !!!!

My FR is about adding a new automation feature to the AQS Modal.

Would be amazing if we could consider the selected text in the active note as a **input** when execute an AQS Modal command. 

## My FR

The idea is simple, if something is selected in the active note, when executing an AQS Modal command, the content that is selected will be presented in the `search-input` field of the AQS modal

📸 Selected Text in Active Note
![C3292CF0-6DC1-48FA-AC31-EBEFF5D8633B](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/85180696/a101e75f-69c2-4c6c-96b3-3dd1049baed8)

📸 AQS Modal Openned with the Search Input with the Selected Text
![009E0DCB-CCC4-4116-A0A8-D18B13879335](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/85180696/df50c1af-e55e-4924-85d9-944398432c88)

## My Worklfow

I use a lot of tags in my YAML/frontmatter and an AQS Modal is the best way to open notes based on *tags* criteria. 

This way, would be extremely fast to if an AQS modal could bring the selected `#tag` in the active note 

---

Thanks for reading this !!!!! I hope you like my suggestion 🙏 🙏 🙏

Let me know if you need more information !!!

Have a great day 🌞

**Comment by tadashi-aikawa** [comment]
Hi, @FelipeRearden :)

It would be possible. However, let me set the status of this issue "gathering interest" for the following reasons🙏

- There is an alternative solution (copy & paste)

**Comment by FelipeRearden** [comment]
> It would be possible. However, let me set the status of this issue "gathering interest" for the following reasons🙏

Hello @tadashi-aikawa !!!!

100% understood. Thanks for considering this FR in a future release :)

> * There is an alternative solution (copy & paste)

If you allow me, I just wanna make a comment about copy & paste...

Many times, I use AQS to quick an open a different note in a new tab, paste something, close this different note and continue my workflow in the main note. 

That why I am asking this FR .... many times I need to paste content from the active `Note A` in `Note B` and I want to use the selection in `Note A` to trigger the AQS modal to open `Note B` in a new tab and paste the content in the clipboard.

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
I see. I usually use a clipboard manager, so I overlooked that. I'll try implementing it 👍

**Comment by FelipeRearden** [comment]
> I see. I usually use a clipboard manager, so I overlooked that. I'll try implementing it 👍 

Thank you very much for trying to implement this feature @tadashi-aikawa !!!!!!! 🙏

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Fix in [v8.11.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.11.0) 🚀

**Comment by tyf2018** [comment]
@tadashi-aikawa 
Hi，I think this function is pretty cool. It seems to only take effect in edit mode now. Can you consider enabling this function in preview mode as well?

Best regards.

**Comment by FelipeRearden** [comment]
> @FelipeRearden
> Fix in [v8.11.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.11.0) 🚀

Thank you very much @tadashi-aikawa !!!!! 

Working perfect on Obsidian Mobile version 1.4.6 :)

Thank you very much @tadashi-aikawa for this feature ☀️

**Comment by tadashi-aikawa** [comment]
>  It seems to only take effect in edit mode now. Can you consider enabling this function in preview mode as well?

@tyf2018 
O.K. I'll try it in the next release 👍

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
I have released [v8.12.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.12.0), and the release version has a small breaking change. Please check it 🙏

**Comment by FelipeRearden** [comment]
> @FelipeRearden
> I have released [v8.12.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.12.0), and the release version has a small breaking change. Please check it 🙏

Hello @tadashi-aikawa !!!!!

Working perfect on version v8.12.0 on Obsidian Mobile 1.4.6 !!!!
Both status `false` and `true` are working perfect !!!! 

I just wanna say thank you for the way that you handle this issue ☀️ now everybody is happy 🎉

I wish you a fantastic day @tadashi-aikawa !!!!!!!
