### ISSUE TITLE
Add ignore setting for Move file to another folder

### ISSUE THREAD

**Issue by charleshan** [tadashi-aikawa/obsidian-another-quick-switcher#18]
There are ignore settings for Normal search, Recent search, and Backlink search but not for Folder search (?) for moving a file to another folder.

**Comment by tadashi-aikawa** [comment]
Hi, @charleshan.

O.K. I'll implement it 👍

**Comment by tadashi-aikawa** [comment]
@charleshan 
I have released to [v4.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.2.0) 🚀

Please confirm whether it works as you expected.

**Comment by charleshan** [comment]
Works great. Thanks :)
