### ISSUE TITLE
Feature Request: Shorten long lines in Grep Search

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#182]
Hi Tadashi!

**problem**  
I noticed that the grep search always shows the full line where a search hit occurs. In some cases, I have very long paragraphs, like this one:
![CleanShot 2023-05-31 at 11 21 45@2x](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/73286100/badd7d3f-7f2e-4db7-92a6-2ff96afb287d)

While some context is useful, displaying the full line here takes up so much space that the other search hits are pushed out of view. 

**suggested solution**  
Therefore, I'd like to suggest some sort of automatic trimming when a search result is too long. I am not sure what a good value for this might be. Maybe everything beyond 100 characters before/after the matching word could be trimmed? If there are multiple matches in one line (e.g. If I had another "growth" in that line) this would become a bit more tricky. Maybe the 100 character limit could be applied to before the first and after the last match then?

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser :)

The ripgrep doesn't have such a feature, but I understand there may be use cases where it's needed. I will consider adding an option 👍

**Comment by tadashi-aikawa** [comment]
LGTM

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/d627347c-82e2-4db6-a747-3ea718d54f4a)

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/8fbb0b42-1b8f-46b4-852a-2eee26e3a48f)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Released in [v8.14.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.14.0) 🚀

**Comment by chrisgrieser** [comment]
thank you 😊
