### ISSUE TITLE
[CSS] Target `. . .` 3 dots inside `another-quick-switcher__status__search-command`

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-another-quick-switcher#183]
### Discussed in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/181

<div type='discussions-op-text'>

<sup>Originally posted by **FelipeRearden** May 30, 2023</sup>
Hello @tadashi-aikawa !!!!!

Would you mind helping me to target this element inside an AQS modal ?

![6BA33AA9-4616-4367-A04C-C3056543565A](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/85180696/8ab12dfb-9d71-4162-866b-b90fd8ab8fe3)

it's inside `another-quick-switcher__status__search-command`

I want to `display:none` this element because I am using some EMOJI/UNICODE as title for some floating modals to make a minimalistic UI 

it is WIP but would be something like this ....

![A45537B4-BFD6-44DE-A749-80814FEF5FDB](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/85180696/45a30c40-21ee-46b6-9d93-7fb33bbbd822)

Thank you very much for the help @tadashi-aikawa !!!!!</div>

**Comment by tadashi-aikawa** [comment]
@FelipeRearden Continue in this issue 👍

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Fix in [v8.11.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.11.0) 🚀

**Comment by FelipeRearden** [comment]
> @FelipeRearden
> Fix in [v8.11.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.11.0) 🚀

Thank you very much @tadashi-aikawa !!!!! 

Working perfect on Obsidian Mobile version 1.4.6 :)

Thank you very much @tadashi-aikawa for this feature ☀️

I wish you a fantastic day!!!!!
