### ISSUE TITLE
[FR] Add support for all readline vi like keybindings please

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/obsidian-another-quick-switcher#186]
When typing any thing (a command or fuzzy finding) only <C-u> of readline Vi keybindings is currently supported. Add support for <C-w> and <C-h> for removing the last word and character (respectively) too please.

Thank you very much

**Comment by tadashi-aikawa** [comment]
Hi, @Archie-2021 :)

> Add support for and for removing the last word and character (respectively) too please.

I consider to implement it 👍

**Comment by tadashi-aikawa** [comment]
@Archie-2021 

> Add support for and for removing the last word and character (respectively) too please.

I am considering adding this feature. Could you tell me with examples of the query input text before and after the command execution?

**Comment by Archie-2021** [comment]
> @Archie-2021 
> 
> > Add support for and for removing the last word and character (respectively) too please.
> 
> I am considering adding this feature. Could you tell me with examples of the query input text before and after the command execution?
> 
> 

I will send you examples as soon as I get home. 

It is basically like when you press control-h , control-w and control-u in an terminal emulator. The first one is basically the same as backspace, the second one does exactly the same thing as pressing control-backspace. And the third one deletes the whole line which is already implemented.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
