### ISSUE TITLE
Render aliases in headings

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#187]
I would love to see aliases in headers be rendered instead of this:

<img width="648" alt="image" src="https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/44113468/2e0dc46d-af20-418e-a572-f0058ec4cb74">

This is one of the headers in markdown:
<img width="633" alt="image" src="https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/44113468/66029b3f-4787-47c9-bb82-e0491db63625">

**Comment by tadashi-aikawa** [comment]
@tim-hilde 
Fixed in [v8.12.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.12.1) 🚀
