### ISSUE TITLE
[Feature Request] User can create search command with predefined condition

### ISSUE THREAD

**Issue by jzhang-brex** [tadashi-aikawa/obsidian-another-quick-switcher#19]
# Use Case

My vault contains personal and work-related notes. I place all work-related notes under the same folder or tag them with `#work`

When I am at work, I want to only search notes related to work. I can start each query with "#work" but it becomes very tedious.

If I am actively working on project-a, I may need to start each query with `#work #project-a`.

# Solution

In the plugin's settings page, users can add a custom search command. Users can specify predefined conditions and other options (e.g. ignore normal path patterns).

For example, I will add a custom search command. Name it "work search". And set the predefined conditions to "#work".  As for the options, we can narrow the search to a specific folder.

The plugins will register this command with Obsidian. Then the user can either access it through the command palette or assign a shortcut.

**Comment by tadashi-aikawa** [comment]
Hi, @jzhang-brex.

I agree with your use case and solution. 

> The plugins will register this command with Obsidian

I will try it as well as I can.

> Users can specify predefined conditions and other options (e.g. ignore normal path patterns).

I will consider the predefined conditions (obviously), but I will not consider the options.

**Comment by tadashi-aikawa** [comment]
@jzhang-brex 
I have released this feature in [v6.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78) 🚀

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. Of course, It would be great to have feedback or bug reports :)

**Comment by rapatel0** [comment]
Not sure if I'm doing something wrong

The hotkey command for a specific search works beautifly but the `:p` doesn't seem to be working with the recommended search 

Config:
Custom command: Projects
Default input: #T/Projects
Priorities:
- Tag match
- Prefix name match
- Name match
- Header match
- Link match
- Last opened
- Last modified

# Hotkey trigger (works perfectly)
<img width="704" alt="image" src="https://user-images.githubusercontent.com/18704704/183893473-2b198ea8-8d3d-4dc5-93fe-a1276934794a.png">

# Recommended search trigger
<img width="696" alt="image" src="https://user-images.githubusercontent.com/18704704/183893875-0297beb4-dec4-4376-9df6-d3b8ef0b9cf7.png">

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @rapatel0 :)

That is a good point out. But unfortunately, the search using `Command Prefix` don't consider `Default Input` and `Ignore prefix path patterns` for now.

I'll consider them by modifying the UI of the dialog. Please wait for the next beta release 👍

**Comment by tadashi-aikawa** [comment]
@rapatel0 
Released in v6.0.0-beta8 🚀

https://user-images.githubusercontent.com/9500018/184126682-0a432bf3-5083-41a1-b3df-7948c5b79328.mp4

**Comment by rapatel0** [comment]
Beautiful This is awesome

**Comment by rapatel0** [comment]
I assume that you're still working on it but. It's not clear how to indicate ignore prefixs. I used newlines to sepearte them but they don't seem to filter correctly, 

<img width="1431" alt="image" src="https://user-images.githubusercontent.com/18704704/184443308-a6624a83-8879-460a-a1f8-14599cb53ba8.png">

**Comment by tadashi-aikawa** [comment]
@rapatel0 
As far as I saw your images, it seems that you didn't set `/` and `Binary Files/` in "Ignore prefix path patterns.

**Comment by tadashi-aikawa** [comment]
Ah.. it is impossible to ignore `/`. So please wait to implement `Includes prefix path patterns`.

**Comment by tadashi-aikawa** [comment]
I have released [v6.0.0-beta10](See https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78#discussion-4239819) 🚀 

@rapatel0 
The new beta version enables you to set `Includes prefix path patterns`. Please try it :)

**Comment by tadashi-aikawa** [comment]
Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀
