### ISSUE TITLE
[FR] Please add an option for using ripgrep to search in other than markdown file formats

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/obsidian-another-quick-switcher#190]
Opening this FR per this:
> @Archie-2021 No, but if you need it, I will implement it. If so, please create an issue.
>

Hey,
Please add an options for searching in other text formats, at least for txt/without extension in Linux text files and HTML, Other formats could be useful too but I don't have any of them from top of my head

Thanks

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
Fixed in [v8.13.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.13.0) 🚀

**Comment by Archie-2021** [comment]
Thank you very much
