### ISSUE TITLE
[FR] add an feature to go to next/previous results

### ISSUE THREAD

**Issue by Archie-2021** [tadashi-aikawa/obsidian-another-quick-switcher#191]
Hey,

Please add a way for us to see all the search results if we need to see more than the first page of the results 

Thanks

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
I attempted an implementation, but it turned out to be more complex than I initially thought, so I've considered a different approach. Instead of paging, I propose displaying all search results, regardless of any set limit. Would this be acceptable? For more details, please watch the attached video.

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/4bc24869-bd4f-429b-8f77-ae4c92bee7f7

**Comment by Archie-2021** [comment]
> @Archie-2021 I attempted an implementation, but it turned out to be more complex than I initially thought, so I've considered a different approach. Instead of paging, I propose displaying all search results, regardless of any set limit. Would this be acceptable? For more details, please watch the attached video.
> 
>  2023-06-18_12h44_58.mp4

I see, yeah it is a good enough solution, I think you can optimize the performance in this way , just hitting a button (I could not see what you used and it shows all the results in slow way, but by default it shows only the first page)

Thanks you very much my friend.

**Comment by tadashi-aikawa** [comment]
@Archie-2021 
I used the following command.

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/c0ecbe2e-0c5c-40fb-a672-44b942cf6568)

It would be slow if you showed thousands of results, but there are no problems if you want to see only hundreds.

**Comment by tadashi-aikawa** [comment]
Released in [v8.14.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.14.0) 🚀

**Comment by Archie-2021** [comment]
> @Archie-2021 
> I used the following command.
> 
> ![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/c0ecbe2e-0c5c-40fb-a672-44b942cf6568)
> 
> It would be slow if you showed thousands of results, but there are no problems if you want to see only hundreds.

Very nice. Yeah it depends on the search tho. If the word is very common thousands or results is possible.

Thanks
