### ISSUE TITLE
[FR]: when no result is found, create note from type "Enter"

### ISSUE THREAD

**Issue by YIRU69** [tadashi-aikawa/obsidian-another-quick-switcher#192]
I would like to request a feature where, similar to a core plugin, I can press the "Enter" key to create a file when searching for a file that does not exist, instead of having to use the mouse to click the Create File button. This way, I can avoid switching back and forth between the keyboard and mouse and stay on the keyboard.
Thank you!

**Comment by tadashi-aikawa** [comment]
Hi, @YIRU69 :)

> This way, I can avoid switching back and forth between the keyboard and mouse and stay on the keyboard.

You can already use the following commands that let us stay on the keyboard 😉 

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/f7894ed7-9ef7-4bf5-ae72-3ff78e5fd31b)

**Comment by YIRU69** [comment]
Thank you so much!
