### ISSUE TITLE
[FR] RipGrep Mobile support

### ISSUE THREAD

**Issue by zanodor** [tadashi-aikawa/obsidian-another-quick-switcher#196]
One can install ripgrep in terminal, probably even without jailbreak. Would be nice to have it on mobile. Are there any limitation issues?

**Comment by tadashi-aikawa** [comment]
The Grep feature uses Node.js API that doesn't allow it to use in mobile. 

https://github.com/obsidianmd/obsidian-releases/blob/master/plugin-review.md#nodejs-and-electron-api
