### ISSUE TITLE
[Feature request] Folder filter

### ISSUE THREAD

**Issue by RenanSantos7** [tadashi-aikawa/obsidian-another-quick-switcher#199]
This plugin could make it possible to filter items based on their location.

This would be useful, for example, to remove templates from the search, which personally bothers me a bit.

**Comment by tadashi-aikawa** [comment]
@RenanSantos7 
You could set `Include prefix path patterns` in "Search commands".

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/e557cab1-b8d7-4a69-a55e-19a3e345fe59)

**Comment by ShravanSunder** [comment]
@tadashi-aikawa is it possible to have it ignore a pattern?
say for example ignore all _archived folder

projects/_archived _=> ignore all files in this folder_
areas/money/_archved _=> ignore all files in this folder_

**Comment by tadashi-aikawa** [comment]
@ShravanSunder 

> is it possible to have it ignore a pattern?  say for example ignore all _archived folder

No. It only filters as a prefix matching. It would be possible if we could support the wildcard pattern or the regex pattern.

**Comment by tadashi-aikawa** [comment]
This issue will be closed for now, as there have been no comments from visitors for a month.
