### ISSUE TITLE
[FR] Restore previous input

### ISSUE THREAD

**Issue by doit132** [tadashi-aikawa/obsidian-another-quick-switcher#200]
When using shortcut keys to open the input box, restore the last search word entered and select.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @doit132 :)

**Comment by tadashi-aikawa** [comment]
@doit132 
Released it in [v11.0.0-beat1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/227) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.

**Comment by tadashi-aikawa** [comment]
@doit132 
Released in [v11.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.0.0) 🚀
