### ISSUE TITLE
option to hide folders icon in "move file to another folder" dialog

### ISSUE THREAD

**Issue by totholz5d** [tadashi-aikawa/obsidian-another-quick-switcher#202]
It would be great to have the option to hide the folders icon (left) and path (right) in the "move file to another folder" dialog

at the moment it looks like this
<img width="629" alt="Screenshot 2023-09-15 at 07 57 19" src="https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/60790281/b6d519c5-2229-4719-a06f-0463aab75d89">

with the option to disable the icon and path it would look like this
![Screenshot 2023-09-15 at 07 57 192](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/60790281/bc4c7adc-e934-4736-ad4d-b55c06dfce70)

Thanks for the great plugin!

**Comment by tadashi-aikawa** [comment]
Hi, @totholz5d :)

You can hide them by using the following CSS.

```
.another-quick-switcher__item.another-quick-switcher__directory_item::before {
  display: none;
}

.another-quick-switcher__item.another-quick-switcher__directory_item
  .another-quick-switcher__item__directory {
  display: none;
}
```

**Comment by totholz5d** [comment]
Hi, 
Unfortunately it doesn't work for me

I created a CSS file with the code above, added it to the obsidian snippets folder and activated it... but it doesn't change anything...

Am I missing something?

**Comment by totholz5d** [comment]
works great, thanks!

**Comment by totholz5d** [comment]
The only thing is that one has to repeat the procedure each time the plugin is updated...

So I will still pledge for an option to disable it in the plugin settings! :)

**Comment by tadashi-aikawa** [comment]
@totholz5d 
If you follow [the CSS snippets rules](https://help.obsidian.md/Extending+Obsidian/CSS+snippets), you should not need to update the CSS every time.
