### ISSUE TITLE
Can't search with folder correctly

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-another-quick-switcher#204]
Hi, @tadashi-aikawa.

I've been using the feature you've mentioned with `folder names/` for a long time already, but recently I've noticed that search is not working anymore the way I expect. Is there something changed in it recently?
For me the search shows only files in subfolders of entered folder and shows the file in that folder only. 

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/8974488/b776b143-01a9-408f-9a24-2bcf3429cfd1)
![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/8974488/d2ec1e4b-baeb-48aa-8867-c42625ebec68)
![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/8974488/0f03317e-472d-4ac6-8788-4074ddce847e)
![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/8974488/7dfc1895-284b-42f9-8be6-20ec8fb6f545)

_Originally posted by @meskill in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/20#issuecomment-1722556532_

**Comment by tadashi-aikawa** [comment]
@meskill
Released in [v9.1.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/9.1.1) 🚀

**Comment by meskill** [comment]
Big thanks!

I've tested it and it's working as expected.
