### ISSUE TITLE
In file search

### ISSUE THREAD

**Issue by tadashi-aikawa** [tadashi-aikawa/obsidian-another-quick-switcher#209]
Like...

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/5efebcf1-d6ef-49ed-aad6-ad38dcee121e

**Comment by windily-cloud** [comment]
Awesome！！！I already thought this plugin was amazing enough, but seeing this once again makes me very excited.  Besides, vim is awesome too !

**Comment by tadashi-aikawa** [comment]
Coming soon...

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/9a91b3cc-8639-47a1-86dd-6905c18f8702

**Comment by tadashi-aikawa** [comment]
Released in [v10.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/210) 🚀

**Comment by windily-cloud** [comment]
Works great, thanks. 

One small flaw though, is that the in-file search is the keyword searched for, but the actual highlighting is a whole line, not sure if that's a problem or not.

![图片](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/30640638/c9d6d8be-b4df-4671-ad71-cb983211908e)

Another small problem is that I searched for `easy` in this post, but one item came up without that keyword as well.

![图片](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/30640638/c46266d8-52c1-4f8a-a52a-fff9a4d3d1e4)

This is test file:

[We choose to go to the moon.md](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/files/12987568/We.choose.to.go.to.the.moon.md)

**Comment by tadashi-aikawa** [comment]
@windily-cloud 
Thank you for your excellent report! I'll look into it 👍

**Comment by tadashi-aikawa** [comment]
> but the actual highlighting is a whole line, not sure if that's a problem or not. Ideally only highlight keywords in file.

It's not a problem at the moment, but I would like to do it if possible.

> Another small problem is that I searched for easy in this post, but one item came up without that keyword as well.

This is a product of coincidence. It's a miracle that the accidental removal of whitespace led to a match with the "easy" that subsequently appeared!! I'll fix it 👍 

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/c831d966-3d3e-43a8-a008-760f5d46c234)

**Comment by tadashi-aikawa** [comment]
@windily-cloud 
Released in [v10.0.0-beta3](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/210) 🚀 

In this version, there are several improvements and new features, but more enhancements are planned before the stable release.

**Comment by windily-cloud** [comment]
There's only one small problem with the test so far, which is that it can't search for special characters containing `[ *`, but it's not a big problem. The others I've used without problems, thanks again for your work!

![图片](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/30640638/0ba7c250-6d28-4971-a0f9-9100549949dc)

**Comment by tadashi-aikawa** [comment]
On my Android device, I've encountered a few bugs. I will fix them soon.

**Comment by windily-cloud** [comment]
> > There's only one small problem with the test so far, which is that it can't search for special characters containing [ *,
> 
> @windily-cloud Released in [v10.0.0-beta5](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/210) 🚀

I have tested the above issues and did not find any bugs.😘😘😁  Thanks for your work!!!

**Comment by tadashi-aikawa** [comment]
Released in [v10.0.0-beta6](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/10.0.0-beta6) 🚀

**Comment by tadashi-aikawa** [comment]
Released in [v10.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/10.0.0) 🚀
