### ISSUE TITLE
Show files that are not .md

### ISSUE THREAD

**Issue by charleshan** [tadashi-aikawa/obsidian-another-quick-switcher#21]
It looks like the plugin doesn't show files that are not .md

Also, it would be great if we can open these files with an option to "Show in default app" with a shortcut.

e.g. Obsidian Another Quick Switcher > Search for a .drawio file > Enter to open in Obsidian

Obsidian Another Quick Switcher > Search for a .drawio file > Control-Enter to open with the default app

**Comment by tadashi-aikawa** [comment]
Hi, @charleshan. Thank you for your FR :)

For now, it is not easy for this plugin to support formats except for Markdown(.md). However, I will consider adding the feature if some people need it (by reacting to this issue).

Kind regards.

**Comment by chrisgrieser** [comment]
I like the idea. Not important, but nice to have to switch to images.

**Comment by brimwats** [comment]
big +1 from me

**Comment by kometenstaub** [comment]
I'd also like to have this feature.

**Comment by ColeFaraday** [comment]
I'd like this feature is well, especially for things like PDF's

**Comment by kalmir** [comment]
+1

**Comment by quangnd159** [comment]
I think we'll need this to show .canvas file down the line, so +1

**Comment by tadashi-aikawa** [comment]
I rarely use canvas because it doesn't support Obsidian Publish. But, on the other hand, many people want to search for it in the AQS. So I plan to implement it soon if possible 👍

**Comment by tadashi-aikawa** [comment]
It's funny... It was supposed to be implemented assuming Markdown, but it works fine even when a non-Markdown file is loaded... 🤔

**Comment by tadashi-aikawa** [comment]
I found that we can use link search (Search target = "link") in the Excalidraw file. (Unfortunately
, not working in Canvas file) 👀 

![image](https://user-images.githubusercontent.com/9500018/209458918-aff7dfc4-9b8c-4cb0-9fd2-b504a53832f9.png)

**Comment by tadashi-aikawa** [comment]
![image](https://user-images.githubusercontent.com/9500018/209460501-3d40e2a3-6ad3-426c-96c8-125b992301cb.png)
![image](https://user-images.githubusercontent.com/9500018/209460504-10bc0678-e64f-48d0-8a86-3278b30aaf25.png)

**Comment by tadashi-aikawa** [comment]
Work fine for me on Windows 🎄 ✨  I'll release `v8.0.0-beta1` 🎁 

- [x] Open dialog to check operation
    - [x] Be able to identify the extension.
        - [x] [[Markdown]]
        - [x] [[Image]]
        - [x] [[Canvas]]
        - [x] [[Excalidraw]]
    - [x] [[Obsidian]] compatible files must be opened in [[Obsidian]]
        - [x] [[Markdown]]
        - [x] [[Image]]
        - [x] [[Canvas]]
        - [x] [[Excalidraw]]
    - [x] [[Obsidian]] unsupported files must be opened with an application associated with [[OS]]
        - [x] `*.js`.
        - [x] `*.css`.
    - [x] insert to editor must work.
        - [x] [[Markdown]]
        - [x] image files
        - [x] [[Canvas]]
        - [x] [[Excalidraw]]
        - [x] `*.js`]
        - [x] `*.css`]
    - [x] show backlinks must work.
        - [x] [[Markdown]]
        - [x] image files
        - [x] [[Canvas]]
        - [x] [[Excalidraw]]
    - [x] show backlinks not working
        - [x] `*.js`
        - [x] `*.css`
            - ❌== files like `hoge.css` and `hoge.css.md` don't work==
- [x] In [[Markdown]] files linked from files.
    - [x] The following files should appear in [[Backlinks]].
        - [x] [[Markdown]]
        - [x] [[Excalidraw]] (from [[🦉Togowl]])
    - [x] [[Backlinks]] not displaying the following files.
        - [x] [[Canvas]] (from [[🦉Togowl]])
            - Embedding notes in [[Canvas]] doesn't seem to work as links.
- [x] [[Outgoing links]] should show the following files (from this file).
    - [x] [[Markdown]]
    - [x] [[Image files]]
    - [x] [[Canvas]]
    - [x] [[Excalidraw]]
- [x] [[Hover Editor]] must also work.
    - [x] [[Canvas]] file to open
- [x] [[Excalidraw]] [x] [[Canvas Editor]] should work outside of the main window.
    - [x] Open a [[Canvas]] file.
- [x] [[Canvas]] file must work even if the current file is empty.
    - [x] Open a [[Canvas]] file.
- [x] [[Canvas]] file should work.
    - [x] [[Backlinks]] should appear
- [x] [[Outgoing links]] does not work in [[Canvas]] files
    - Embedding a note in [[Canvas]] does not seem to work as a link.
- [x] [[Excalidraw]] files also work.
    - [x] [[Outgoing links]] should be displayed.
    - [x] [[Backlinks]] should be displayed.

**Comment by quangnd159** [comment]
Just installed the beta on mac. Works great so far.

**Comment by tadashi-aikawa** [comment]
@charleshan @kalmir @ColeFaraday @quangnd159 @brimwats @chrisgrieser @kometenstaub 
🎅 **Thanks for your patience. I have released this feature in v8.0.0-beta1** 🚀 

I have tested the major cases only on Windows, but some bugs might remain. It would be great to test the beta version using BRAT. 😄 

For details, please see https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/134.

P.S. @quangnd159, Super quick! thanks! 🙏

**Comment by brimwats** [comment]
works fine on win 11!!

**Comment by tadashi-aikawa** [comment]
Released in [v8.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.0.0-beta2) 🚀 

https://user-images.githubusercontent.com/9500018/209675872-c139f8f7-85e9-4734-9cdc-88f120388abe.mp4

**Comment by tadashi-aikawa** [comment]
Released in [v8.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/8.0.0) 🚀
