### ISSUE TITLE
Feature request: If file is open, go to that tab—don't open a dublicate tab

### ISSUE THREAD

**Issue by rasmusrhl** [tadashi-aikawa/obsidian-another-quick-switcher#216]
I often end up with many dublicate tabs. 
This is because "another quick switcher" always creates a new tab—also if the file is already open.
Solution: if a file is already open, go to that tab—don't open a dublicate tab.

PS: thanks for "another quick switcher" 😊

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @rasmusrhl :)

I agree with your suggestion. I'll implement it 👍

**Comment by hustrjh** [comment]
@tadashi-aikawa I also look forward to this feature. 😊 Maybe this plugin called [Obsidian opener](https://github.com/aidan-gibson/obsidian-opener) could help you.

**Comment by tadashi-aikawa** [comment]
@rasmusrhl @hustrjh 
Released it in [v11.0.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/227) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.

Honestly, I have never needed this feature, so your feedback would be very helpful 🙏

**Comment by hustrjh** [comment]
@tadashi-aikawa Perfect! Thanks a lot! 👍

**Comment by rasmusrhl** [comment]
Thanks! I can't get BRAT to work, because I'm noob. But I'm sure you have done a great job 😎😎

**Comment by tadashi-aikawa** [comment]
@rasmusrhl @hustrjh 
Released in [v11.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.0.0) 🚀
