### ISSUE TITLE
Add heading level to header search

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#217]
Would be great to have the option to add the header level to the header search

Ideally as an addition to the "Hide gutter icons" option, as I only want to see the heading levels

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @tim-hilde :)

That looks good. I’ll consider it👍

**Comment by tadashi-aikawa** [comment]
Hi, @tim-hilde :)

I tried to add a setting to Another Quick Switcher, but then I realized that it's unnecessary with the use of CSS. I'm sharing this with you.

```
/* Another Quick Switcher */
.another-quick-switcher__item__title__header {
  list-style: none;
}
.another-quick-switcher__item__title__header::before {
  padding-right: 5px;
  font-weight: bold;
  color: lightgray;
}
.another-quick-switcher__item__title__header1::before {
  content: "H1";
}
.another-quick-switcher__item__title__header2::before {
  content: "H2";
}
.another-quick-switcher__item__title__header3::before {
  content: "H3";
}
.another-quick-switcher__item__title__header4::before {
  content: "H4";
}
.another-quick-switcher__item__title__header5::before {
  content: "H5";
}
.another-quick-switcher__item__title__header6::before {
  content: "H6";
}
```

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/468fca3c-874b-4321-bb36-ba7ec1353368)

**Comment by tim-hilde** [comment]
Oh great! That's perfect! Thank you
