### ISSUE TITLE
Bug: 'In file search': If note is 'pinned', return/mouseclick on search result item opens a duplicate note 

### ISSUE THREAD

**Issue by avirosso** [tadashi-aikawa/obsidian-another-quick-switcher#218]
First: Thanks for the great 'In file search'-Feature!

One problem/bug: If I search in a 'pinned' note, return/mouseclick on search result item opens a duplicate note  in a new tab.

Thanks in advance!

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @avirosso :)

That consideration had been overlooked. Given that it is named 'In file search', it should indeed be corrected 👍

**Comment by tadashi-aikawa** [comment]
@avirosso 
Released it in [v11.0.0-beat1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/227) 🚀 

If you use BRAT, I would appreciate it if you could check it out before the official release.

**Comment by tadashi-aikawa** [comment]
@avirosso 
Released in [v11.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.0.0) 🚀

**Comment by avirosso** [comment]
Great - thank you very much!

**Comment by avirosso** [comment]
Hi,

I don't find a 'reopen' button/command, so I comment:

I had tested that in Version 11.0.0 and it worked.

But now - in Version 11.2.1 - it no longer works: If I use the command 'In file search' in a pinned Note, the following happens:

- No search modal opens
- Instead a new, empty tab opens
- The following error message is in DevTools:

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'getValue')
    at InFileModal.indexingItems (plugin:obsidian-another-quick-switcher:5263:52)
    at InFileModal.init (plugin:obsidian-another-quick-switcher:5183:16)
    at showInFileDialog (plugin:obsidian-another-quick-switcher:5540:15)
    at Object.checkCallback (plugin:obsidian-another-quick-switcher:5624:9)
    at Jq (app.js:1:1792093)
    at e.executeCommand (app.js:1:1793657)
    at e.onTrigger (app.js:1:1155885)
    at e.handleKey (app.js:1:748623)
    at e.handleKey (app.js:1:748736)
    at t.handleKey (app.js:1:748945)
```

**Comment by tadashi-aikawa** [comment]
Hi. @avirosso 

Could you please create a new issue for this?

**Comment by avirosso** [comment]
OK - I have opened a new issue (#231)
