### ISSUE TITLE
 Quick Switcher screen does not scroll when you use the ctrl+j(k)/n(p) keys to navigate

### ISSUE THREAD

**Issue by tonygrr** [tadashi-aikawa/obsidian-another-quick-switcher#22]
### Explanatory illustration

![gif](https://user-images.githubusercontent.com/72566774/152859290-db39844e-fe11-4421-a3b4-8f38666ee3aa.gif)

At the same time, if you use the arrow keys to navigate - everything works fine (which I do at the end of the gif).

P.S.: thank you very much for adding the ability to navigate the j/k keys; the vim mod users appreciate it.

I hope that fixing this bug will not cause difficulties.

**Comment by tadashi-aikawa** [comment]
Hi, @tonygrr. Thank you for your bug report :)

It wasn't easy when I implemented it. However, I have found a workaround. So I will fix it and release it soon 👍

**Comment by tadashi-aikawa** [comment]
@tonygrr 
I have released to [v4.2.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.2.1) 🚀

Please confirm whether it works as you expected.

**Comment by tonygrr** [comment]
@tadashi-aikawa yes, everything works great now! Thank you so much (:
