### ISSUE TITLE
[BUG] MOBILE - Search Commands: Floating Checkbox stopped Working on Version 10.0

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#221]
Hello @tadashi-aikawa !!!!

Just to let you know that the **FLOATING** checkbox from `Search Commands` is not working ONLY on Obsidian Mobile on version `10.0`

ℹ️ I just updated from `9.2` to `10.0` 
ℹ️ Obsidian Mobile is updated in the latest public release 

**Here is some points from my own investigation:**
● You can use the `mobile emulation` feature on desktop investigate the issue.
● When opening the Console on `mobile emulation` I could see that on Obsidian Mobile there is no `.prompt.another-quick-switcher__floating-prompt `

Look at this images…

📸 Obsidan Mobile - Emulation on Desktop ❌
![IMG_0434](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/85180696/74dde6ad-292a-46b4-a108-534dfda5bf1c)

📸 Obsidian Desktop ✅
![IMG_0432](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/85180696/e5035153-f622-4c66-9d47-9491ec8d72a9)

<hr>

Let me know if you need any additional tests. 

I hope you can reproduce on your end 🙏 🙏 🙏

I wish you a fantastic day ☀️

**Comment by tadashi-aikawa** [comment]
Thank you, @FelipeRearden :)

Fix on [v10.1.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/10.1.0-beta2) 🚀

**Comment by FelipeRearden** [comment]
> Thank you, @FelipeRearden :)
> 
> Fixed on [v10.1.0-beta2](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/10.1.0-beta2) 🚀

Thank you very much @tadashi-aikawa !!!!!

Working perfect on version  10.1.0-beta2 on Obsidian Desktop and Obsidian Mobile (emulation). When we got the public version, I will test on my main vault on iPadOS. 

Thank you very much @tadashi-aikawa for the fix 🙏
I wish you a fantastic day ☀️

**Comment by tadashi-aikawa** [comment]
Released in [v11.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.0.0) 🚀

**Comment by FelipeRearden** [comment]
> Released in [v11.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.0.0) 🚀

Working perfect on version `11.0.0` on Obsidian Mobile on iPadOS 17.2 

Thank you very much @tadashi-aikawa !!!!!!!!!!
