### ISSUE TITLE
Setting to enable selected item to Open In New Tab

### ISSUE THREAD

**Issue by vaneyah** [tadashi-aikawa/obsidian-another-quick-switcher#222]
Hi,

Is there a way to open in a new tab by default, rather than replace the current note/tab we have open?

Thank you,
Chris

**Comment by tadashi-aikawa** [comment]
Sorry for my late answer, @vaneyah.

Yes, you can. For example, you should bind the "Enter" key as a shortcut for the 'open in new tab' command.

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/33550402-c4b8-4501-b82b-affd2344fadb)

**Comment by vaneyah** [comment]
Amazing, exactly what I wanted - thank you!!
