### ISSUE TITLE
[Feature Request] - Include/Exclude based on frontmater matching

### ISSUE THREAD

**Issue by rapatel0** [tadashi-aikawa/obsidian-another-quick-switcher#223]
As a user, I'd like to be able to index / slice or search based on values contained within frontmatter when creating a custom search. Ideally using more than one key to slice

## Example of files being searched for in a custom search
FIle 1 - cheese project 
```yaml
doc-type: task
task-type: project
```
FIle 2  - ease project
```yaml
doc-type: task
task-type: project
```
FIle 3 - swiss cheese
```yaml
doc-type: task
task-type: oneoff
```

Ideally I can create a custom search that only operates on `doc-type == task` and `task-type== project`. Then a search for `ease` would rank
- FIle 2  - ease project
- FIle 1  - cheese project

(*File 3 wouldn't  appear in results*)

## Proposed methods
- Add additional ranking criteria
- Allow for passing a dataviewjs pages array with a custom query

**Comment by tadashi-aikawa** [comment]
Sorry for my late answer, @rapatel0.

I agree with your opinion. Might this issue also be relevant?
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/205

**Comment by rapatel0** [comment]
Great yeah. Sorry, i didn't see that issue. I'll close this issue

**Comment by rapatel0** [comment]
Duplicate of #205
