### ISSUE TITLE
[Feature Request]: The view is "really" floating and not modal, in the sense that you can move the view and something else can have the focus

### ISSUE THREAD

**Issue by fieldrabbit21** [tadashi-aikawa/obsidian-another-quick-switcher#228]
Hi Tadashi-Aikawa,

Thank you for your work on this fantastic plugin! Something that I use every day.

I it possible to make the view "really" floating and not modal, 
in the sense that you can move the view and something else can have the focus/

Kind regards,
Henry

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @fieldrabbit21 :)

At the moment, we do not have plans to implement this feature, as Another Quick Switcher is a plugin related to the quick switcher.

Best regards.

**Comment by fieldrabbit21** [comment]
ok, thanks for your feedback. and many thanks for a great plugin!
