### ISSUE TITLE
how does one use the property search?

### ISSUE THREAD

**Issue by zeltak** [tadashi-aikawa/obsidian-another-quick-switcher#229]
Hi and thx for the latest update

I have to say im confused on how to use  the property search :)

lets say I have yaml files with `ratings` and `status` ie

```
---
tags:
  - chicken
  - chicken-wings
  - soup
  - thailand
status: 5
rating: 3
---
```

how does one look for files with status lets say `3` and tag=soup?

thx!

Z

**Comment by tadashi-aikawa** [comment]
@zeltak 
It is not supported yet :)

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.0.0#:~:text=Search%20by%20properties

> Specifying a property key is not supported yet
> https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/205

**Comment by zeltak** [comment]
ahh I see :)

thx!
