### ISSUE TITLE
Include special letters in search

### ISSUE THREAD

**Issue by Gnopps** [tadashi-aikawa/obsidian-another-quick-switcher#23]
Thanks for developing this plugin! I use it for the recent search feature.

Would to be possible to incorporate [this functionality](https://forum.obsidian.md/t/kinder-search-for-special-letters/27990) in it? I.e. that when typing for example "u" you get results showing "ü" as well.

**Comment by tadashi-aikawa** [comment]
Hi, @Gnopps. Thank you for your FR :)

If you mean that you want to search files with accents/diacritics or not, I think it is possible by using [logic](https://stackoverflow.com/questions/990904/remove-accents-diacritics-in-a-string-in-javascript). Do you think it is all right?

**Comment by tadashi-aikawa** [comment]
@Gnopps 
I have released [v4.3.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.3.0) 🚀  Please confirm whether it works as you expected. 

![image](https://user-images.githubusercontent.com/9500018/153596503-e6982828-eb6a-409e-aa30-14e52659044e.png)

**Comment by Gnopps** [comment]
Wow, that was quick! Thank you!

I managed to find a note with "Ü" using "U", great!

However, typing "Ö" or "O" did not find "Ø", Would that kind of syntax be possible?

**Comment by Gnopps** [comment]
Works very well, thank you for your work!
