### ISSUE TITLE
Keyboard not appearing on mobile

### ISSUE THREAD

**Issue by csss1234** [tadashi-aikawa/obsidian-another-quick-switcher#230]
I think this only happens if I trigger AQS immediately after obsidian being launched.

the quick switcher appears, but the keyboard doesn’t. I have to tap the search field to get a cursor. 

Wouldn’t be much of a problem except I run into it repeatedly each day. Because 90% of the time, after I  open obsidian i am immediately searching for a note!

tested on sandbox, still a problem

Increasing search delay has no effect

**Comment by tadashi-aikawa** [comment]
Hi, @csss1234 :)

I have released in [v11.2.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.2.1) 🚀

In version 11.2.1, we added a restriction that prevents commands from being executed until Obsidian has finished loading data.
