### ISSUE TITLE
How do you bind Ctrl+space?

### ISSUE THREAD

**Issue by axelson** [tadashi-aikawa/obsidian-another-quick-switcher#232]
Hi, thanks for the plugin! I'm really enjoying it! :tada:

I'm trying to bind Ctrl+space to "preview" but I'm having trouble

Things I've tried:
- `Mod 32` (this is the keycode for the space bar key from https://www.toptal.com/developers/keycode)
- `Mod Space`
- `Mod Spacebar`
- `Mod (blank space)`

Do you have any suggestions on what else to try?

**Comment by tadashi-aikawa** [comment]
Sorry for my late answer, @axelson :)

Regrettably, the code assigned to the Space key conflicts with the space character used as a delimiter alongside modifier keys. I will explore potential implementations to enable configuration of the Space key 👍

**Comment by axelson** [comment]
One week isn't late at all to me! On my open source projects I often take a month to respond :sweat_smile:

Thank you for looking into it!

**Comment by tadashi-aikawa** [comment]
@axelson 
Released in [v11.3.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.3.0) 🚀

Now, you can set `Mod Space` 😊

**Comment by axelson** [comment]
It works great! Thank you so much!
