### ISSUE TITLE
I encounted an error when use Grep

### ISSUE THREAD

**Issue by MerliniKing** [tadashi-aikawa/obsidian-another-quick-switcher#236]
rg worked in cmd.exe:
![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/10217348/dd9172aa-148f-4114-995e-7cff73cc1a7a)

But failed in Grep search:
![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/10217348/70ea487e-310d-4428-822e-833996421bda)

**Comment by tadashi-aikawa** [comment]
Hi, @MerliniKing :)

Could you try specifying the absolute path to ripgrep in the 'Ripgrep command' option?

![image](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/9500018/d0657415-0ff2-442a-a953-e0fad3db5c2a)

ex: `C:/Users/tadashi-aikawa/scoop/shims/rg.exe`

**Comment by MerliniKing** [comment]
it's ok!
