### ISSUE TITLE
support obsidian-quick-preview

### ISSUE THREAD

**Issue by calmwaves111** [tadashi-aikawa/obsidian-another-quick-switcher#242]
Thank you very much for your hard work, this plugin is so feature-rich, I have been using this plugin for more than a year, instead of the core plugins quick switch and search

Now I have a suggestion, the preview function of this plugin is not convenient, I think the hover preview is more user-friendly, I hope to support this plugin [obsidian-quick-preview](https://github.com/RyotaUshio/obsidian-quick-preview)

I've already raise an issue in that plugin and the developer replied that they need support from another-quick-switcher  https://github.com/RyotaUshio/obsidian-quick-preview/issues/8

Perhaps you could consider my suggestion

**Comment by tadashi-aikawa** [comment]
Thank you for your suggestion, @calmwaves111 :)

Unfortunately, Another Quick Switcher already provides its own Preview function, and I do not intend to change it to a pop-up format. (I want to avoid supporting both and having the behavior depend on other plugins.)

I appreciate your understanding.
