### ISSUE TITLE
[FR] Option to disable auto-embed on "insert to editor" with PDFs

### ISSUE THREAD

**Issue by Glint-Eye** [tadashi-aikawa/obsidian-another-quick-switcher#244]
Right now, if I use the "insert to editor" or "insert to editor in background" commands on a pdf, AQS will automatically create an embed for that file. I prefer to use PDFs as a reference and most of the time i do not need an embed. So i'll have to remove the embeds manually afterwards.

An option to deactivate auto-embeds for pdfs would be great.

Cheers :)

**Comment by tadashi-aikawa** [comment]
Hi, @Glint-Eye :)

This behavior seems to be the default for the Obsidian API (for plugins) when generating links. However, unlike images, PDFs are often not embedded. Therefore, I'll try changing the default behavior. (If we receive an issue about this, I'll consider making it an option.)

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
Released in [v11.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.5.0) 🚀

**Comment by Glint-Eye** [comment]
> @Glint-Eye Released in [v11.5.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.5.0) 🚀

Awesome, as always :).

Thx a lot :)
