### ISSUE TITLE
Bug: Clear search button disappears when Another Quick Switcher is enabled

### ISSUE THREAD

**Issue by Comprehensive-Jason** [tadashi-aikawa/obsidian-another-quick-switcher#246]
For some reason, enabling Another Quick Switcher causes the _Clear search_ button in the Search core plugin view to disappear.
The button ceases to exist.

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/assets/68677082/9f45f3e4-8adc-455c-8e60-017b2c63a562

This was tested as plugin version 11.5.0 in the Sandbox vault. Here's the vault's debug info:

SYSTEM INFO:
	Obsidian version: v1.6.5
	Installer version: v1.5.8
	Operating system: Windows 10 Home 10.0.22631
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 0

**Comment by tadashi-aikawa** [comment]
Thank you for your report, @Comprehensive-Jason :)

I'll fix it in the next release 👍

**Comment by tadashi-aikawa** [comment]
@Comprehensive-Jason 

Released in [v11.5.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/11.5.1) 🚀
