### ISSUE TITLE
Feature request: Option to show aliases on top if alias exists

### ISSUE THREAD

**Issue by ryadaj** [tadashi-aikawa/obsidian-another-quick-switcher#25]
It would be excellent if aliases were shown on top instead of file name, so reverse the view shown in the screenshot:
<img width="760" alt="Screen Shot 2022-02-23 at 11 29 47" src="https://user-images.githubusercontent.com/82765301/155363243-70ae6a48-ad43-412a-bda8-e277690b1e12.png">

The native quick switcher does this by default
<img width="806" alt="Screen Shot 2022-02-23 at 11 31 57" src="https://user-images.githubusercontent.com/82765301/155363504-c1c6d9df-c0ff-4e1a-8a72-13668e0b92d8.png">

**Comment by ryadaj** [comment]
Amazing, thanks!!

**Comment by tadashi-aikawa** [comment]
@ryadaj 

I have released to [v4.4.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.4.0) 🚀

Please confirm whether it works as you expected.

**Comment by ryadaj** [comment]
Works perfectly :)

<img width="795" alt="Screen Shot 2022-02-27 at 08 41 40" src="https://user-images.githubusercontent.com/82765301/155884848-351edede-d32b-4487-b3e8-d3364b136b99.png">
