### ISSUE TITLE
"Ignore diacritics" finds only first file when multiple spellings are used

### ISSUE THREAD

**Issue by Wildphinn** [tadashi-aikawa/obsidian-another-quick-switcher#250]
**EDIT:** Apologies, it works as expected (I was having the file open). Please file this issue as… a non-issue 😅

The "Ignore diactricis" option is amazing, but I found an edge case: suppose you have two files named (as happens in French)
- `événement`
- `évènement`

Searching for whatever spelling such as `événement` or `evenement`only returns one hit instead of the two files it would be expected to find (different diacritics for the same word). 

![CleanShot 2024-08-29 at 16 25 17@2x](https://github.com/user-attachments/assets/11c1d3e6-7746-45cf-8805-7be19ae07401)

Unless I'm missing something?

**Comment by kometenstaub** [comment]
_Replying here as well._

Make sure that you don't have the file open you're searching for, though, as it is excluded.

It does return both for me.

<img width="691" alt="image" src="https://github.com/user-attachments/assets/5e344aee-fe55-4d26-965b-cf33f830821f">

And:

<img width="691" alt="image" src="https://github.com/user-attachments/assets/5f80a344-bd5b-4b80-9b12-c11e3c343000">

**Comment by kometenstaub** [comment]
And since you were using file name search, not recent search, it also works for me:

<img width="695" alt="image" src="https://github.com/user-attachments/assets/d44de05b-308e-4218-b7f7-36766d855da7">

**Comment by Wildphinn** [comment]
You're absolutely right. Apologies for missing this, it does work as expected. Thanks for the correction!

**Comment by tadashi-aikawa** [comment]
@Wildphinn 
I’m glad to hear that!

@kometenstaub 
Thanks for following!

---

The behavior where the currently open file does not appear in the suggestions is likely to cause trouble. I will create an issue template to prevent this from happening again.

**Comment by tadashi-aikawa** [comment]
I have added the issue-form-template 👍 

![image](https://github.com/user-attachments/assets/cf3fda11-c28c-4961-8eab-ede753dc9098)
