### ISSUE TITLE
[Bug] Fuzzy search option is reset after Obsidian restart

### ISSUE THREAD

**Issue by nicolnt** [tadashi-aikawa/obsidian-another-quick-switcher#252]
### Check for Commonly Missed Points

- [X] Files not shown in the suggestions are not an active file. (An active file is not shown in the suggestions.)

### Summary

The toggle option _Allow fuzzy search for "Search target"_ keeps getting reset when I restart Obsidian.

### Steps to Reproduce in the Sandbox Vault

This happens both ins sandbox vault without any other non default configuration or plugin and my main vault with Obsidian Sync.

### Expected Behavior

To keep the option enabled until I manually disable it myself

### Actual Behavior

Option is reset to default (toggled off)

### Obsidian Version

v1.6.7

### Another Quick Switcher Version

v11.6.0

### OS

Windows 10 Pro 10.0.19045

### Notes

![](https://private-user-images.githubusercontent.com/9500018/361601600-e68adb9c-0442-4b41-a402-69d2ff5b9f14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMDU2MDEsIm5iZiI6MTcyNjIwNTMwMSwicGF0aCI6Ii85NTAwMDE4LzM2MTYwMTYwMC1lNjhhZGI5Yy0wNDQyLTRiNDEtYTQwMi02OWQyZmY1YjlmMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MTNUMDUyODIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmFhNzMzZDUxZjI3MTMyYTZiMTI0N2VhMjViZWMyMjZkMjAwYTM0ZTI3NDUxYzI1NzE5MTFiMjk3YTlkYjQxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NtiLC1NoHbIr4g1-EvJfedvMSoQ3y4pdbXLARCCjMfo)

<details>
  <summary>Debug info (sandbox vault)</summary>

```
SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.5.3
	Operating system: Windows 10 Pro 10.0.19045
	Login status: logged in
	Catalyst license: insider
	Insider build toggle: off
	Live preview: on
	Base theme: adapt to system
	Community theme: none
	Snippets enabled: 0
	Restricted mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Another Quick Switcher v11.6.0

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

</details>

**Comment by tadashi-aikawa** [comment]
Hi, @nicolnt :)

Did you press the 'Save' button?

![image](https://github.com/user-attachments/assets/803bd589-7bac-45ce-84b9-91d8ac718027)

**Comment by nicolnt** [comment]
Oh I'm sorry, I was not aware of that "Save" button.
Is there a reason why it's not just automatically saved? All the other plugins in my experience don't need this extra step.

**Comment by tadashi-aikawa** [comment]
> Is there a reason why it's not just automatically saved?
I don't remember the detailed reason, but updating the settings every time they are changed caused an issue when adding a new search command.
