### ISSUE TITLE
[feature request] Restore previous input

### ISSUE THREAD

**Issue by hyperphysin** [tadashi-aikawa/obsidian-another-quick-switcher#255]
Could you please add an option to restore the last typed input when launched?

**Comment by tadashi-aikawa** [comment]
Can you achieve this with "Restore last input"?

![image](https://github.com/user-attachments/assets/511162e7-fa06-47ce-ad21-0e766054aaf2)

**Comment by hyperphysin** [comment]
It doesn't work with me.

![Screenshot 2024-10-07 at 12 05 21 AM](https://github.com/user-attachments/assets/2d41e208-fe83-4df3-9857-baf8bce0085f)
I turned the option on.

![Oct-07-2024 00-13-53](https://github.com/user-attachments/assets/0f652daa-d6c1-46a7-8012-2dc528526d17)
Last input's not restoring.

Maybe it's a bug?

**Comment by hyperphysin** [comment]
> @hyperphysin Can you achieve this with "Restore last input"?
> 
> ![image](https://private-user-images.githubusercontent.com/9500018/373937056-511162e7-fa06-47ce-ad21-0e766054aaf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMjgwODksIm5iZiI6MTcyODIyNzc4OSwicGF0aCI6Ii85NTAwMDE4LzM3MzkzNzA1Ni01MTExNjJlNy1mYTA2LTQ3Y2UtYWQyMS0wZTc2NjA1NGFhZjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDZUMTUxNjI5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWZlOGU2MzQwMTk1YjAxNzNmZmEyNzBmYjBjNjVkZDkwYTBkNjdlMDQyOGFmY2Q1MTU1NWIyNWE0MDZkZTNkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.eqgs-wTFaBblMdoLMlo3DozI83w5Ny-lrKSGAwe3-Lc)

It doesn't work with me.

![Screenshot 2024-10-07 at 12 05 21 AM](https://github.com/user-attachments/assets/b04a0f3e-600f-49be-a945-143037bdabc0)

I turned the option on.

![Oct-07-2024 00-13-53](https://github.com/user-attachments/assets/121c1be8-b557-4b34-8905-e9ea0f05ed34)

Last input's not restoring.

Maybe it's a bug?

**Comment by tadashi-aikawa** [comment]
@hyperphysin 
Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

**Comment by hyperphysin** [comment]
> @hyperphysin Unfortunately, I couldn't reproduce it. Could you tell me the reproduction steps in the sandbox vault?

Weiredly, uninstalling and installing again the plugin solved the issue.
Sorry to waste your time and thank you for making this useful plugin :)

**Comment by tadashi-aikawa** [comment]
I’m glad to hear that!

**Comment by chrisgrieser** [comment]
@hyperphysin I also noticed "restore last input" not working for me. Turns out, that setting is effectively disabled by the "use selection words as input" setting. Disabling that one makes "restore last input" work for me.

@tadashi-aikawa I think it might make sense to maybe add to the setting description that these two setting cannot be enabled at the same time to avoid such confusion? 🙏

**Comment by hyperphysin** [comment]
> @hyperphysin I also noticed "restore last input" not working for me. Turns out, that setting is effectively disabled by the "use selection words as input" setting. Disabling that one makes "restore last input" work for me.
> 
> @tadashi-aikawa I think it might make sense to maybe add to the setting description that these two setting cannot be enabled at the same time to avoid such confusion? 🙏

aha! That was why. Thank you for letting me know that.

**Comment by tadashi-aikawa** [comment]
@chrisgrieser (@hyperphysin )
Thank you for the helpful information! That was completely unexpected, so I’ll try to revise it to make both options compatible👍

**Comment by tadashi-aikawa** [comment]
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/259

**Comment by tadashi-aikawa** [comment]
@chrisgrieser @hyperphysin 
Released in [v12.0.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/12.0.1) 👍
