### ISSUE TITLE
add keybind to close selected file in opened file search

### ISSUE THREAD

**Issue by svonjoi** [tadashi-aikawa/obsidian-another-quick-switcher#256]
#116

**Comment by svonjoi** [comment]
after a while using this nice feature, i noticed that i constatly need to clean up some already unnecesary files. The idea is from nvim again, there the most popular pickers like telescope.nvim have this ability and i miss it so much in obsidian =)

**Comment by tadashi-aikawa** [comment]
LGTM👍

**Comment by tadashi-aikawa** [comment]
*Supplemental Information*
I considered removing closed files from the selection options, but I decided to keep them for consistency with other commands.

**Comment by tadashi-aikawa** [comment]
@svonjoi 
Released in [v12.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/12.1.0) 🚀

**Comment by svonjoi** [comment]
hey, thanks for the update, i tested and saw that element after closing it still apearing in the list untill the list is opened again

**Comment by tadashi-aikawa** [comment]
@svonjoi 
Thank you for checking. So far, it’s working as expected.
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/256#issuecomment-2466084362

**Comment by svonjoi** [comment]
i'm blind :D
