### ISSUE TITLE
Feature request: allow searching contents of files

### ISSUE THREAD

**Issue by quinncomendant** [tadashi-aikawa/obsidian-another-quick-switcher#26]
Before using Obsidian, I used [Notational Velocity](https://notational.net/), nvAlt, and FSnotes. These programs were optimized with the same design: a single field is used both for creating notes and searching. When entering the title for a new note, it searched the full text of all notes at the same time, displaying the results below the search field. This functionality is similar to Obsidian's _Quick Switcher_ exempt the latter does not search the contents of all notes, only their file names. 

Does Another Quick Switcher support full text search in the contents of notes? (I tried it, but it seems this is not an option.) Why not?

Would it be difficult to add this functionality? If performance might be an issue, perhaps you can use `mdfind` or `ripgrep` internally to quickly search text content.

**Comment by tadashi-aikawa** [comment]
Hi, @quinncomendant :)

> Does Another Quick Switcher support full text search in the contents of notes?

No.

> Why not?

The reason for we can search the contents of all notes by the `Search in all files` command. I respect the ideology of Obsidian, therefore I'll not implement it for quick switcher UI.

Best regards.

**Comment by hicaicai** [comment]
I really like your plugin, this plugin is the one I use the most, but it's strange that every time I want to search the contents of a file, I have to switch the Search in all files command. It's a bit of a pain and I don't want to have to switch back and forth. I know you respect the ideology of Obsidian, but the plugin itself is giving another option. Whether you implement it or not, thank you very much for developing such a great plugin.

**Comment by quinncomendant** [comment]
Just use the [Omnisearch](https://github.com/scambier/obsidian-omnisearch) plugin, it's what we're looking for: a single field is used both for creating notes and searching. It's really good.

**Comment by hicaicai** [comment]
Ok, cool. Thank you.
