### ISSUE TITLE
[FR] option to search links and backlinks at once

### ISSUE THREAD

**Issue by hyperphysin** [tadashi-aikawa/obsidian-another-quick-switcher#263]
Could you please add an option to search links and backlinks at once?

**Comment by tadashi-aikawa** [comment]
Hi, @hyperphysin :)

Is this issue the same as the one you're referring to? If so, I would appreciate it if you could watch that issue.

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/144

**Comment by hyperphysin** [comment]
> Hi, @hyperphysin :)
> 
> Is this issue the same as the one you're referring to? If so, I would appreciate it if you could watch that issue.
> 
> #144

Yes, they are the same.
