### ISSUE TITLE
Feature Request: Priority sort by base file name

### ISSUE THREAD

**Issue by scpedicini** [tadashi-aikawa/obsidian-another-quick-switcher#27]
I really enjoy "Another-quick-switcher" but recently I'm running into an issue where the folder is given more "weight" in a query than the file name.

For example, I have a folder called "_CSharp_" with hundreds of notes. I need to find a note called "_Using the Sharp library_" which was in a different folder called "_Misc_". I accessed "Quick Switcher: Recent Search" typed in "_sharp_", but unfortunately was overwhelmed with all the notes from the "_CSharp_" folder *first*. Could we add an option or feature change to perform sorting in the following manner:

1. Sort by Base File Name
3. Than by Recently Accessed 
4. Than By Folder Name
5. Than By Tag Name

On the surface, this feels like the most user intuitive search method.

**Comment by tadashi-aikawa** [comment]
Hi, @scpedicini. Thank you for your FR :)

> I accessed "Quick Switcher: Recent Search" typed in "sharp", but unfortunately was overwhelmed with all the notes from the "CSharp" folder first

Perfectly agree. I have been annoyed with such an issue, too. So I'll implement it this weekend 👍

**Comment by tadashi-aikawa** [comment]
@scpedicini 
I have released to [v4.6.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.6.0) 🚀 

Please confirm whether it works as you expected.

**Comment by tadashi-aikawa** [comment]
And released [v4.7.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.7.0) 🚀 

It includes sort order improvements. It is not only for `Filename recent search` but also for `Normal search`.

**Comment by scpedicini** [comment]
![sharp example](https://user-images.githubusercontent.com/2040540/161434965-8d4f5575-d9f2-41b3-8683-5a029d1ef315.png)
@tadashi-aikawa 
thanks for the update. I think it might need a few adjustments. In this example, I think the correct order should have been:
1. CAT-578 Sharp on Lambda => recently accessed today
2. Sharp npm library => last accessed a week ago
3. Detecting Spikes in Volume (Two Sharp knocks) => last accessed in 2020 last year
4. Using ffmpeg in Node
5. Using VLC in .NET
6. Youtube API Manual Scraping
7. Yield Generator in C#

So always return the files with base name containing the search string, then sort those results by recent access, then return the CSharp folder results (also sorted by recent access). Does that make sense?

**Comment by tadashi-aikawa** [comment]
@scpedicini 
Thank you for your confirming :)

Did you run the new command, `Filename recent search` certainly? (not `Recent search` )

**Comment by scpedicini** [comment]
Yeah haha I literally just discovered that a half a second ago which does exactly as I described. I think I'll probably use that as my primary search method from now on. Is there any advantage to using the regular "Recent Access Quick Switcher Search" that I might be missing?

**Comment by tadashi-aikawa** [comment]
Glad to hear that!

The advantage is that you don't have to be aware of where the term you are searching for is in the filename, tag, or directory.

I will try both for a while 👍

**Comment by scpedicini** [comment]
@tadashi-aikawa 
Sounds good. I've been doing some testing with the new Filename recent search today and found a possible issue, and wanted to get your thoughts on it.

I think it might be a good idea to priority sort whole word matches first. I was trying to find a note related to danmaku games and typed the word "hell" but it showed many other notes at the top.

![whole word enhancement](https://user-images.githubusercontent.com/2040540/161453584-bcc9217e-e3c5-455b-8e58-3460c486bfdc.png)

**Comment by tadashi-aikawa** [comment]
Right. I think it seems better in the case of the language whose delimiter is whitespace.

However, it reduces performance, so I want to add the feature with a new option. Would you create a new issue?

**Comment by scpedicini** [comment]
@tadashi-aikawa
Good point about delimiters, I've created a new FR here: 
https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/30

**Comment by tadashi-aikawa** [comment]
Thanks! So I'll close this issue.
