### ISSUE TITLE
Can exclude certain folders or files from the result

### ISSUE THREAD

**Issue by z-jason** [tadashi-aikawa/obsidian-another-quick-switcher#3]
For example, we can exclude templates files from the search result.

On top of this, it'll be nice to introduce the profile concept where each profiles has its own configuration (e.g. which folders to exclude). And the plugins can provide a way to quickly switch between profiles.

**Comment by tadashi-aikawa** [comment]
Hi. @z-jason. Thank you for the feature request!

I had already added this one related to `Backlink Search,` so I will implement it related to other searches.

>  it'll be nice to introduce the profile concept where each profiles has its own configuration

Nice! I think so, too. So, I will add this feature to the roadmap and create another issue. 👍

**Comment by tadashi-aikawa** [comment]
I have closed this issue because there is no response in a week.
