### ISSUE TITLE
Feature Request: Sort by Whole Word (Optional Flag) 

### ISSUE THREAD

**Issue by scpedicini** [tadashi-aikawa/obsidian-another-quick-switcher#30]
Request for a checkable option that prioritizes sorting by search queries which match whole words. As @tadashi-aikawa has mentioned, this needs to be optional since it can potentially impact performance and because sentence tokenization is different depending on the language (Chinese, Japanese, etc do not have spaces between the words.)

![image](https://user-images.githubusercontent.com/2040540/161563217-e1bcfe5a-f41f-4527-8338-e54ec723658f.png)

In this case, we are trying to search for the word "hell", but many other partial matches show up *before* the results containing whole words, eg "Exceed Bullet Hell Shmups".

**Comment by tadashi-aikawa** [comment]
Mmm.. It seems time for me to refactoring sort logic 😅

**Comment by tadashi-aikawa** [comment]
As far as I tried, I added this feature without any option because there is little performance reduces.

**Comment by tadashi-aikawa** [comment]
@scpedicini 

I released [v4.8.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.8.0) 🚀 

Please confirm whether it works as you expected.

**Comment by scpedicini** [comment]
![whole-word-search](https://user-images.githubusercontent.com/2040540/162626940-b3d1276a-ea7d-4b57-af26-efb23da34e23.png)

 @tadashi-aikawa Just ran the same query as last time, it looks great! At this point, Obsidian should just hire you to write the official quick switcher. 😁
