### ISSUE TITLE
Option to copy currently selected item from the suggestions list to input text field

### ISSUE THREAD

**Issue by hakonhagland** [tadashi-aikawa/obsidian-another-quick-switcher#31]
Thanks for creating this nice plugin. It is really helpful. 

I often use `CTRL+O` instead of `CTRL+N` when I want to create a new note. Then I use `SHIFT+ENTER` to create a new note from inside the quick switcher. However, it often useful to create a note that has a similar name to an existing note. To avoid typing the whole name again (if you have a long name) it would be great to be able to press `TAB` (for example) in the quick switcher. Then the currently selected item from the suggestions list would be copied into the search input text field. And the user could edit that text to create a new file name.

**Comment by tadashi-aikawa** [comment]
Hi, @hakonhagland. Thank you for your PR :)

Looks good me. I'll implement it 👍

**Comment by hakonhagland** [comment]
@tadashi-aikawa Thank you!

**Comment by tadashi-aikawa** [comment]
Looks good 😄 

![2022-04-10](https://user-images.githubusercontent.com/9500018/162607624-f2f71511-68df-402b-a908-72ad46f82148.gif)

**Comment by hakonhagland** [comment]
Fantastic job! I will test this now :smile:

**Comment by hakonhagland** [comment]
It works perfectly here! Thank you!!

**Comment by tadashi-aikawa** [comment]
@hakonhagland 
Thank you for your quick confirming!

I Released [v4.8.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.8.0) 🚀
