### ISSUE TITLE
Feature Request: when enabling Show Directory, show full directory path

### ISSUE THREAD

**Issue by onepointfivem** [tadashi-aikawa/obsidian-another-quick-switcher#33]

**Comment by meskill** [comment]
+1 for this feature, as for me I have such picture sometimes.

![image](https://user-images.githubusercontent.com/8974488/167080054-c3d0cd44-bc6c-4fbf-81da-2372df487166.png)

**Comment by tadashi-aikawa** [comment]
Thank you for sharing your backgrounds :)

**Comment by tadashi-aikawa** [comment]
@meskill @onepointfivem 
I have released [v4.13.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.13.0) 🚀

**Comment by tadashi-aikawa** [comment]
![image](https://user-images.githubusercontent.com/9500018/168420404-6060d13a-7da6-46e3-891a-6a69aeef36d4.png)
