### ISSUE TITLE
How to wait for MarkdownView to become defined after creating new file? 

### ISSUE THREAD

**Issue by hakonhagland** [tadashi-aikawa/obsidian-another-quick-switcher#35]
Hi. I have a question. I want to insert a template (frontmatter) that depends on the title of the note (actually it depends on which tags are present in the title) after I press `SHIFT+ENTER` in the switcher modal to create a new file.

I have written a private plugin that registers to the `create` event like this:

```typescript
		this.registerEvent(
			this.app.vault.on('create', (file: TFile) => {
				this.createFile(file, this.app);
			})
		);
```

the `createFile()` method then tries to insert the frontmatter (but currently fails):

```typescript
private createFile(new_file: TFile, app: App) {
	const view = app.workspace.getActiveViewOfType(MarkdownView);
	if (view !== null) {
  	// .... more code here
	}
}
```

The problem is that the `view` is `null`. I guess this code is called too early, that is before the view is ready. Any idea how I can wait until the view is ready here? (I checked the code, and [this](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/blob/master/src/app-helper.ts#L75) looks like the place where the view is being defined, right?)

**Comment by tadashi-aikawa** [comment]
Hi, @hakonhagland 

I think you can call `app.vault.adapter.append(filePath, content)`. It could add contents to the file directly without using the editor.

**Comment by hakonhagland** [comment]
## Reply
> I think you can call `app.vault.adapter.append(filePath, content)`. It could add contents to the file directly without using the editor.

Yes it seems to work fine if I feed it `file.path` from the `file: TFile` coming in to the `app.vault.on('create'...` callback. The problem is that the create event seems to be fired by the obsidian startup process also, so I need to separate out which create events I should handle (I only want those that are generated by the quick switcher when pressing `SHIFT+ENTER`). Another issue is that I need to position the cursor at the tag line after having filled out the front matter template, like this:
```
---
aliases:
tags: tag1, tag2, <cursor here>
creation date: 2022-04-13 20:48
modification date: 2022-04-13 20:48
---
```

at the place indicated by `<cursor here>` in the above snippet. So I guess I need to access the editor then and  `app.vault.adapter.append()` will not help with that..

So I abondoned this approach since I found another event that seems to also solve the issue more easily. Namely the `app.workspace.on('file-open'...` event:

```
this.registerEvent(
			this.app.workspace.on('file-open', (file: TFile) => {
				this.insertOrUpdateFrontmatter(file, this.app);
			})
		);
```

This event seems to be triggered later than the `create` event from `app.vault`, so in this case the markdown view is not `null`. The app.workspace file-open event will be triggered also when you open existing files, but if  I check if `view.data === ''` it will most likely mean that a new file was created (since the file is empty). Another thing that gave me some headache was that I had forgotten to switch off "Trigger Templater on new file creation" (from the Templater plugin settings page):

![templater-settings](https://user-images.githubusercontent.com/6708379/163251861-84ea9e5b-21ee-468b-a02d-357676b604a5.png)


this caused templater to erase the frontmatter I just had inserted. So this switch must be in "off" position.

**Comment by tadashi-aikawa** [comment]
Thank you for your details :)

> So I abondoned this approach since I found another event that seems to also solve the issue more easily. Namely the app.workspace.on('file-open'... event:

I think that is the best workaround, too 👍
