### ISSUE TITLE
FR: Open in Hover Editor

### ISSUE THREAD

**Issue by Aaron-Bopp** [tadashi-aikawa/obsidian-another-quick-switcher#36]
Nothingislost just added this to the default quick switcher, but I would love to have this feature for the quick switcher I actually use :P
Obviously, this would require people to have the Hover Editor plugin as well. I'm not sure how possible inter-plugin operation like this works, but it would be greatly appreciated.

**Comment by tadashi-aikawa** [comment]
Hi, @Aaron-Bopp. Thank you for your FR :)

It looks great. I'll try it with reference to https://github.com/nothingislost/obsidian-hover-editor/pull/41 👍

**Comment by tadashi-aikawa** [comment]
@Aaron-Bopp 
I have released to [v4.9.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.9.0) 🚀

Please confirm whether it works as you expected.

**Comment by Aaron-Bopp** [comment]
Works great! Thank you so much!
