### ISSUE TITLE
FR: Suggester that shows only files in the current folder

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#38]
pretty much what the title says. Might be useful to reduce noise.

just FYI, I also opened a similar issue at Quick Switcher++, since it could also fit them?
https://github.com/darlal/obsidian-switcher-plus/issues/44

**Comment by tadashi-aikawa** [comment]
LGTM :)

**Comment by tadashi-aikawa** [comment]
Released in v6.0.0-beta11 🚀 

[For details]
`Add a <current_dir> directive that means the current directory, in "Include prefix path patterns" and "Exclude prefix path patterns"` in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78

**Comment by tadashi-aikawa** [comment]
Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀
