### ISSUE TITLE
FR: search specific metadata key: value 

### ISSUE THREAD

**Issue by tychovk** [tadashi-aikawa/obsidian-another-quick-switcher#39]
# Use case
I love the ability to search for tags. However, I've found tags to be too limiting to describe what kind of note/type a note is, so I've switched to using mainly custom metadata as key plugins also use those (e.g. Breadcrumbs). However, using the search and metadata does not work well together.

# Solution
In navigating my vault, I would want to be able to use metadata as filters, e.g. the query:
status: "in progress" project: table paint
Would already show notes that have metadata "status" with value containing "in progress", metadata "project" containing table, and the note title containing "paint".

Thanks for all your efforts.

**Comment by tadashi-aikawa** [comment]
Hi, @tychovk. Thank you for your FR :)

It is not easy to support it immediately, but I would like to do it in the future 👍

**Comment by tadashi-aikawa** [comment]
@tychovk
I have closed this issue and continue to #205.
