### ISSUE TITLE
Bug: Duplicate Icons with Supercharged Links in Heading Search

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#40]
Not entirely sure whether the issue is on Supercharged Links' end, or this plugin's end, but the new heading search leads to duplicate headings 

https://github.com/mdelobelle/obsidian_supercharged_links/issues/109

<img width="268" alt="Pasted image  2022-05-05 15 20 42" src="https://user-images.githubusercontent.com/73286100/166943255-b918d4fb-54cb-42dd-a05a-0566b0f8f611.png">

---

The plugin adds elements for icons based on existing css elements. This line is responsible for adding the needed the elements for icons to Another Quick Switcher: https://github.com/mdelobelle/obsidian_supercharged_links/blob/master/main.ts#L147

I am no entirely certain, but I think the issue arises from that fact that the heading search suggester has two classes affected at the same time due to the nesting of headings, it could be that some selector name changes on this side could solve this.

**Comment by tadashi-aikawa** [comment]
Probably, it doesn't need to add an icon on `Heading search`. When there is `another-quick-switcher__item__title__header` class, you will get it as expected if `Supercharged Links` ignore the operation.

![image](https://user-images.githubusercontent.com/9500018/167070392-f8a6cd90-3b51-406f-a62e-7bc960288451.png)

**Comment by chrisgrieser** [comment]
has actually been solved by a PR for sueprcharged links a while ago.
