### ISSUE TITLE
Feature Suggestion: Open Note Linking to Unresolved Link instead of Unresolved Link

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#44]
I noticed that I actually use AQS not to create unresolved links, but rather delete the link as soon as I find them via AQS. So I was wondering whether it would be possible to have an option to open the note that creates does the unresolved linking instead of opening the unresolved, so that you can easily remove it?

either globally via settings, or as yet another modifier action in the prompt.

**Comment by tadashi-aikawa** [comment]
> I noticed that I actually use AQS not to create unresolved links, but rather delete the link as soon as I find them via AQS

Me, too :) But I think it is a bit complicated situation. So if anyone else agrees with the suggestion, I want to consider it.

**Comment by tadashi-aikawa** [comment]
I am afraid of degradation, but it works fine for now 👍 

https://user-images.githubusercontent.com/9500018/209432074-13cb6cdb-e52d-42d0-a44c-da44ba425f63.mp4

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Released in [v7.7.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.7.0) and [v7.7.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.7.1) 🚀
