### ISSUE TITLE
[Feature Request] Ability to remove ghost image for non existing items 

### ISSUE THREAD

**Issue by japanese-goblinn** [tadashi-aikawa/obsidian-another-quick-switcher#46]
I'd like to have this setting so that search items looks more consistent

<img width="636" alt="image" src="https://user-images.githubusercontent.com/33631005/168470765-4504fcdd-b544-4f1e-8cad-a8bb1ac724fe.png">

**Comment by japanese-goblinn** [comment]
Hey! Well, I'm not star my notes, but I guess it'll be nice too. For now I think it'll fine to add smth like "show accessory images" toggle (or "minimalist mode" but it's not super descriptive) and add description that this disable/enable stars and other possible images in future.

**Comment by tadashi-aikawa** [comment]
Released in [v4.14.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/4.14.0) 🚀
