### ISSUE TITLE
Display of an alias matched by queries

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#5]
Right now, only file names are searched, but not aliases, for which you still require the quick switcher plugin. I think when aliases are searched, the quick switcher can be fully substituted

**Comment by chrisgrieser** [comment]
ah, no I see what the issue was – as opposed to the quick switcher your plugin does not display the current note and its aliases when searching.

That is a subtle but good improvement to search, it only confused me since I was testing aliases of course with the note I have currently open 🤦 😅 

However, I noticed another small issue: The alias is used for matching, but it is not _displayed_ in the suggester itself. I think it would make sense to show the alias itself, too, so the user knows why a note appears in the search results.
<img width="376" alt="Screenshot 2021-10-16 15 37 57" src="https://user-images.githubusercontent.com/73286100/137589648-a6bafff3-3aa0-499c-a029-2d74077528be.png">

**Comment by tadashi-aikawa** [comment]
> it only confused me since I was testing aliases of course with the note I have currently open 🤦 😅

I know how you feel. I have the same mistakes until now, although I am a developer of this plugin. 😅 (confirm the behavior only)

> The alias is used for matching, but it is not displayed in the suggester itself. I think it would make sense to show the alias itself, too, so the user knows why a note appears in the search results.

I agree. We decided that users would know what the alias was in many cases, so we had set a lower priority for it. I will try to support to display of an alias matched by queries.

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Please let us know your opinion.

If it shows all aliases on the suggestion item, does it satisfies your requirement?. Because why it is effortless to implement than to display only matched aliases.

**Comment by chrisgrieser** [comment]
All aliases could be a bit much when you multiple aliases. Hm. How about this:

For every alias, you generate a separate item in the suggester. Those items have the alias symbol and the name of the alias, but to the right, they have the original filename instead of the parent folder's name.

Would that maybe work?

**Comment by tadashi-aikawa** [comment]
Thank you for your reply!

> All aliases could be a bit much when you multiple aliases

I think so, too..

> For every alias, you generate a separate item in the suggester.

If I respect the policy of Obsidian, it seems to be best. However, it also appears to be a bit noisy when we use `Recent Search`.

![image](https://user-images.githubusercontent.com/9500018/140630028-0be1467d-f686-4b05-a199-4f2fcbf7b7f2.png)

Based on the above, I would like to keep this issue, `Display of an alias matched by queries`, and try it implement again :)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
I have added the feature and pushed the latest commit.

I replaced core logic, so there might be some bugs. Therefore, I will use it for a while, and I'll release it as `v2.0.0` when it works correctly.

If you do not mind, It would be great to try the latest source code (not version updated yet) :)

https://user-images.githubusercontent.com/9500018/141674322-4312e75c-f319-4d56-bbf6-f8793f937f9e.mp4

**Comment by chrisgrieser** [comment]
The aliases have more padding to the left than the file title, otherwise this look fine too me! Maybe highlight the alias that is being matched?

**Comment by tadashi-aikawa** [comment]
Thanks for your reply!

> The aliases have more padding to the left than the file title

This is what I intended, but it might not need. I'll format the layout and release it :)

**Comment by tadashi-aikawa** [comment]
I have released as v2.0.0 (and 2.0.1) 🚀
