### ISSUE TITLE
Hotkey Guides Conflict with Supercharged Links

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#51]
Not sure what causes this, but the hotkey guides seem to do something with the DOM, so that the Supercharged Links Icons stop working for the entries with hotkey guide, while all others still work? 😵‍💫 

(potentially related to #40?)

See also https://github.com/mdelobelle/obsidian_supercharged_links/issues/122

![image](https://user-images.githubusercontent.com/73286100/173320629-9761e81e-b67f-43dc-a621-0281f5fbae33.png)

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser.

Would you tell me the reproduction procedure in sandbox vault? I don't use `Supercharged Links` and could not make the situation.

**Comment by chrisgrieser** [comment]
Hi, sorry for the late response.

Reproducing it is a bit complicated, since you need some setup. So I made a "minimal test vault" for you, where I reproduced the issue (same as above, all notes should get the icon). 

➡️ [AQS Debug Test Vault.zip](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/files/8991841/AQS.Debug.Test.Vault.zip)

**some notes**
- I use Obsidian 0.14.15, with AQS version 4.14 since I am staying on the public release
- The latest release from Supercharged Links is a bit outdated, so I made PRs to fix them (since it's only changing one line of code) to it would work with AQS and some other plugins again. [However, that PR hasn't been merged yet.](https://github.com/mdelobelle/obsidian_supercharged_links/pull/102) Therefore, used the [`main.js` from my fork](https://github.com/chrisgrieser/obsidian_supercharged_links/blob/patch-2/main.js), where I really only updated [this one line](https://github.com/chrisgrieser/obsidian_supercharged_links/blob/patch-2/main.js#L2742) to include the up-to-date selectors for omnisearch and AQS. For AQS versions before 4.14 this worked totally fine.

<img width=30% alt="Pasted image 2022-06-27 14 11 24" src="https://user-images.githubusercontent.com/73286100/175938238-daada765-0b8a-4498-ab87-864f2d890852.png">

**Comment by tadashi-aikawa** [comment]
Thanks! I’ll try it at a later :)

**Comment by kometenstaub** [comment]
Hotkey guide should be appended to item__entry not item__title.

Then they are next to the folders, however, so the CSS would need to be updated.

**Comment by tadashi-aikawa** [comment]
Thx! @kometenstaub

**Comment by tadashi-aikawa** [comment]
I'll fix soon for mobile.
![image](https://user-images.githubusercontent.com/9500018/176176355-56dfae63-b5c6-447a-a781-9a101274a060.png)

**Comment by tadashi-aikawa** [comment]
Released in [v5.1.4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/5.1.4) 🚀
