### ISSUE TITLE
[Feature Request] : Shortcut keys customization

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-another-quick-switcher#52]
The new features in version 4.14 are very useful!

A small suggestion, the shortcut key of Ctrl+Number, can users customize it as Alt+Number key? Because I think Alt+Number is easier to press.

Best regards.

**Comment by tadashi-aikawa** [comment]
Hi, @tyf2018.

OK. I'll add the option in next release 👍

**Comment by tadashi-aikawa** [comment]
Released in [v5.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/5.0.0) 🚀
