### ISSUE TITLE
Use only ctrl or cmd in instructions depending on OS

### ISSUE THREAD

**Issue by kometenstaub** [tadashi-aikawa/obsidian-another-quick-switcher#55]
It would be great to declutter the instructions. 

I think it could be done by setting a variable to either ctrl or cmd depending on the OS. 

https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/blob/5b34145b37287b7580f7f5a7c0da01b681ec946e/src/ui/AnotherQuickSwitcherModal.ts#L291-L293

In one of my plugins, I do it like this.
https://github.com/kometenstaub/obsidian-linked-data-vocabularies/blob/2eb4a8b206a2d8b455dc556f3d797c92c440c258/src/ui/LOC/suggester.ts#L72

**Comment by tadashi-aikawa** [comment]
Hi, @kometenstaub. Thank you for your sharing :)

I agree with you 👍
