### ISSUE TITLE
[feat] open in pop-out window

### ISSUE THREAD

**Issue by kometenstaub** [tadashi-aikawa/obsidian-another-quick-switcher#63]
I would appreciate another option that lets me open a file in a pop-out window (Obsidian 0.15+) instead of just in a hover editor.

**Comment by tadashi-aikawa** [comment]
Hi, @kometenstaub. Thank you for your FR :)

I want to, but in my Windows environment, it shows the following popup instead of the one we expected.

![image](https://user-images.githubusercontent.com/9500018/175770454-fc039adf-44f5-4d4f-8f4d-4796040071c8.png)

I had attempted three ways (not in public API), but they were the same 😇 

- `app.workspace.openPopout`
- `app.workspace.openPopoutLeaf`
- `app.commands.executeCommandById("workspace:open-in-new-window")`

On the other hand, it worked perfectly if I executed them in chrome dev tools. (of course in Obsidian, too)

It would be very helpful if you knew the workaround or anything :)

**Comment by kometenstaub** [comment]
That should work though:

https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/08e4e1f131023bf2264f83d4a8345bbb9081edd7/src/main.ts#L1798

**Comment by tadashi-aikawa** [comment]
That uses `app.workspace.openPopoutLeaf` and not working in my environment.

**Comment by kometenstaub** [comment]
Huh, that's odd. It's working for me on Linux on 0.15.2.

**Comment by tadashi-aikawa** [comment]
Maybe it is a problem about Windows...

**Comment by tadashi-aikawa** [comment]
Mmm... Excalidraw can open new pop-out window in my environment !?

**Comment by tadashi-aikawa** [comment]
I continue to survey 👍

**Comment by tadashi-aikawa** [comment]
It works in `onChooseSuggestion` method 🤔

**Comment by tadashi-aikawa** [comment]
I figured out how the problem was caused.

That is very strange... it causes **when push Ctrl key and open pop-out window**.

So should I give up on assigning this feature to hotkeys with the `Ctrl` key? 😭

**Comment by kometenstaub** [comment]
Ah, I can reproduce.

![screenshot](https://user-images.githubusercontent.com/83140328/175774857-e30b2092-65fd-4e15-8574-74b2f72fc2b6.png)

![screenshot2](https://user-images.githubusercontent.com/83140328/175774868-237d3830-cd5d-44ba-a055-7f99c06d5c9e.png)

**Comment by kometenstaub** [comment]
It does work with something like `mod-H` though

**Comment by tadashi-aikawa** [comment]
Looks good! There is no need to include Enter. And easier to push 👍

**Comment by kometenstaub** [comment]
I'm not saying that it's the hotkey to choose, but it's probably not the worst choice.

**Comment by tadashi-aikawa** [comment]
@kometenstaub 
Released in [5.1.0-beta3](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/62#discussion-4162184) 🚀 

I ended up to assigned `Mod + p` and `Mod + Shift + p` keys from `P` in `Popout`.

Thank you again for the opportunity that noticed me how to implement this feature. I have wanted to open the files in AQS, so I'm very glad now 😄

**Comment by kometenstaub** [comment]
That seems to clash with emacs keys, which cannot be turned off.

**Comment by tadashi-aikawa** [comment]
Ah.. I forgot it 😅

**Comment by tadashi-aikawa** [comment]
Released in [5.1.0-beta4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/62#discussion-4162184) that uses `Mod + o` and `Mod + Shift + o` 🚀

**Comment by kometenstaub** [comment]
Works beautifully, thank you! :)
