### ISSUE TITLE
[feat] when no result is found, create note from query in same pane on enter

### ISSUE THREAD

**Issue by kometenstaub** [tadashi-aikawa/obsidian-another-quick-switcher#64]
When creating notes on my phone, I like using the quick switcher for it because there isn't much space for extra buttons.

When there is no search result, it would be great if a note could be created from the query on enter. This would match the default quick switcher behaviour and also make creating notes on devices without external keyboards possible.

**Comment by tadashi-aikawa** [comment]
I will try to add a "create button" for mobile because if it uses Enter, I often create a new file unintentionally without noticing there is no result.

**Comment by tadashi-aikawa** [comment]
Released in [v5.3.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/5.3.0) 🚀
