### ISSUE TITLE
Update issue on Obsidian public release (0.14.15)

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#66]
While creating the test vault for #51, I noticed that seems to be a small issue with AQS installing the wrong version for users with Obsidian 0.14.15. According to your release notes, it is only from AQS 5+ that Obsidian 0.15+ is required. However, when installing AQS in a new vault, it does not install AQS 4.14, but AQS 4.9.

**Comment by tadashi-aikawa** [comment]
Thank you @chrisgrieser :)

I have fixed it. Could you confirm it?

**Comment by chrisgrieser** [comment]
can confirm, works now!
