### ISSUE TITLE
[Feature Request] Option to show File Paths under the File Name

### ISSUE THREAD

**Issue by Glint-Eye** [tadashi-aikawa/obsidian-another-quick-switcher#71]
For longer File Names paired with longer Folder Names the entries get very squeezed and aren't very nice to read anymore. I would actually prefer a display of the File path beneath the name of the File. Making it an option between the way it is now, would be great.

Great plugin btw :)

**Comment by tadashi-aikawa** [comment]
Hi, @Glint-Eye. Thank you for your FR :)

I'll add an option about layout 👍

**Comment by tadashi-aikawa** [comment]
![image](https://user-images.githubusercontent.com/9500018/177263519-6830cb02-9a95-4f54-a137-6ee55e1b7182.png)

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
Released in [v5.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/5.2.0) 🚀
