### ISSUE TITLE
[Feature Request] Customizing Search Result Priorities

### ISSUE THREAD

**Issue by Glint-Eye** [tadashi-aikawa/obsidian-another-quick-switcher#72]
It would be great if search result sorting could be customized. For example by name, recency, last modified etc.
Possibly even with an own definable hierarchy for sorting priorities.

Cheers :)

**Comment by tadashi-aikawa** [comment]
Perfectly I agree. I was going to add a feature like your FR 👍

**Comment by tadashi-aikawa** [comment]
@Glint-Eye 
I have released this feature in [v6.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78) 🚀

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. Of course, It would be great to have feedback or bug reports :)

**Comment by FelipeRearden** [comment]
> I have released this feature in [v6.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78) 🚀

Hello @tadashi-aikawa !!!!

Just to let you know start testing this feature and is working perfect on version `beta-4`

🔬 What I tested so far -> 2 notes from 2 different paths:
- Nested Tags
- Default input with 2 tags (#work #status/done)
- inline tags 
- YAML tags
- YAML tags with the format `tags: [tag1,tag2]`
- YAML tags with the format `tags: \n-\stag1\n-\stag2]`

💪 I am gonna put more testing hours after #53 but I thought that would be a good idea to start giving feedback. 

💙 You have no idea how excited I am about version `6.0.0` 

👀 I let you know if I have more feedbacks :) 

☀️ Have a great day!!!

**Comment by tadashi-aikawa** [comment]
Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀
