### ISSUE TITLE
Layout in Minimal theme is off 

### ISSUE THREAD

**Issue by tim-hilde** [tadashi-aikawa/obsidian-another-quick-switcher#73]
The layout is off when using the minimal theme. Icons on the left are no shown correctly:

![SCR-20220701-9nq](https://user-images.githubusercontent.com/44113468/176828427-b5243fd2-986a-45b8-b850-e270d1340c37.png)

**Comment by tadashi-aikawa** [comment]
Hi, @tim-hilde.

You can show icons by the following CSS.
![image](https://user-images.githubusercontent.com/9500018/176985076-7b4093f0-45a2-4b83-912f-a3cd79e9bb82.png)

If you don't want to show icons, you can do it via settings.
![image](https://user-images.githubusercontent.com/9500018/176985091-d62a296d-a7ba-42c1-a359-64be15d350d1.png)

**Comment by tadashi-aikawa** [comment]
Let me close this issue because no one has answered.
