### ISSUE TITLE
[Feature Request] - Pinned Searches

### ISSUE THREAD

**Issue by rapatel0** [tadashi-aikawa/obsidian-another-quick-switcher#77]
It would be great to define some custom searches that can be pinned to the initial modal. 

For example. I use the `#T/Project` tag for notes that contain projects. I would love to have something that prefills the searchbox with "#T/Project" and then I can sub search amongst the results

Requirements:
- Pinned searches can be defined in options using a simple string. 
- By default the modal (or modal view) starts a default list of pinned searches.

**Comment by tadashi-aikawa** [comment]
Hi, @rapatel0. Thank you for your FR :)

I think https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/19 will satisfy your requirement. What do you think?

**Comment by rapatel0** [comment]
Yeah This is clearly a duplicate of that request. Happy to link and close

**Comment by rapatel0** [comment]
Duplicate of #19

**Comment by tadashi-aikawa** [comment]
@rapatel0 

I have released this feature in [v6.0.0-beta4](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78) 🚀

If you use [BRAT](https://github.com/TfTHacker/obsidian42-brat), please confirm whether it works as you expected. Of course, It would be great to have feedback or bug reports at #19 :)

**Comment by tadashi-aikawa** [comment]
Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀
