### ISSUE TITLE
bug：I installed ripgrep, but the plugin doesn't recognize it.

### ISSUE THREAD

**Issue by tyf2018** [tadashi-aikawa/obsidian-another-quick-switcher#79]
I installed ripgrep, but the plugin doesn't recognize it.
ob：0.15.9
plugin version: 6.0.0-beta4

![CopyQ BdSBfk](https://user-images.githubusercontent.com/56342788/183361243-511260f2-eb3c-4373-b007-cf41934539f8.png)

![CopyQ HWJquH](https://user-images.githubusercontent.com/56342788/183361333-098edc9d-41f0-446c-a388-d5ba303a3c79.png)

**Comment by tadashi-aikawa** [comment]
@tyf2018 
Would you tell me your executed command?

```
$ rg --version
ripgrep 12.1.1 (rev 7cb211378a)
-SIMD -AVX (compiled)
+SIMD +AVX (runtime)
```

**Comment by tyf2018** [comment]
> $ rg --version
> ripgrep 12.1.1 (rev 7cb211378a)
> -SIMD -AVX (compiled)
> +SIMD +AVX (runtime)


An error will be reported after your command is executed.

Here is a screenshot after the previous compilation was done, maybe it will be useful?

![CopyQ rfObVn](https://user-images.githubusercontent.com/56342788/183365518-957d8b3e-3b0c-41b1-8ef0-ab43d0248341.png)

**Comment by tadashi-aikawa** [comment]
@tyf2018 
It looks good 🤔 Does it shows the same output in cmd.exe?

**Comment by tyf2018** [comment]
> Does it shows the same output in cmd.exe?

yes
![CopyQ MmUpAO](https://user-images.githubusercontent.com/56342788/183419246-15de941a-8777-4e5f-a519-99fdb86111ac.png)

**Comment by tadashi-aikawa** [comment]
@tyf2018 
Did you restart Obsidian after installing ripgrep?

**Comment by tyf2018** [comment]
> @tyf2018 Did you restart Obsidian after installing ripgrep?

yes，many times.

**Comment by tadashi-aikawa** [comment]
@tyf2018 
I have released 6.0.0-beta5 that outputs debug logs as follows.

![image](https://user-images.githubusercontent.com/9500018/183428748-ed2b7af2-b11d-498e-8361-221aa05f3a99.png)

Would you upgrade it and capture the error message in devtools?

**Comment by tyf2018** [comment]
@tadashi-aikawa 
![CopyQ EAawKH](https://user-images.githubusercontent.com/56342788/183432326-7f7c3593-fcdf-4024-836b-ec5c175ef85e.png)

Best regards.

**Comment by tadashi-aikawa** [comment]
@tyf2018 
Thank you! But sorry... I included mistaken in the 6.0.0-beta5. So I have released 6.0.0-beta6.

**Comment by tyf2018** [comment]
@tadashi-aikawa 
Thanks！The command can be started, but the search speed seems slow? Maybe it's because there are too many notes? The vault has about 11,000 notes.

The 2nd search even caused the ob to crash.

**Comment by tadashi-aikawa** [comment]
@tyf2018 
> The command can be started

Hmm... That's strange. I didn't fix it except for showing debug log 😅 

Search speed is as well as in the terminal. It shows spent time in the devtool's console if debug is enabled.

![image](https://user-images.githubusercontent.com/9500018/183441689-4ad1d98b-15f1-4549-aec9-08742c8c5ff7.png)

![image](https://user-images.githubusercontent.com/9500018/183441985-19b488a4-dd82-48b4-ac23-7cec6bbe13c8.png)

**Comment by tadashi-aikawa** [comment]
If you store markdown files in the mounted storage (ex: Dropbox, Box), it seems slow both in Obsidian and Terminal.

**Comment by tyf2018** [comment]
> If you store markdown files in the mounted storage (ex: Dropbox, Box), it seems slow both in Obsidian and Terminal.

I am indeed using a third-party synchronization tool: https://www.jianguoyun.com/

In that case, it's really a pity.

Best regards.

**Comment by tadashi-aikawa** [comment]
@tyf2018 

I have improved the Grep feature as well as I can. Please see https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78#discussioncomment-3392381.

If slow in v6.0.0-beta13, there's nothing more I can do 😇
