### ISSUE TITLE
Feature Request: New Note Location

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#8]
The addition of `cmd + shift` was a great idea!

Ad far as I can tell, it always places the new note in the Vault root. Would it be possible to add some customization where new notes get placed?

Ideally, the new note creation would trigger another suggester where you can select a folder. And Subsequently, the new note gets placed at that location. 🙏

**Comment by tadashi-aikawa** [comment]
I see. Simple is important, I think so, too.

Additionally, while `Move file to another folder` command can only move to a folder that exists, I'll try to be able to also a one that doesn't exist yet. (It means that create a new folder)

As as result,

1. You press `shift + enter`
2. This plugin creates a new file
3. You run a new command, then a new suggester is opened, where you can search only for folders
You select one folder.
4. This plugin moves the new note to a directory selected from suggestions

**Comment by chrisgrieser** [comment]
that sounds great, looking forward to it :)

**Comment by tadashi-aikawa** [comment]
Hi, @chrisgrieser.

I have implemented it as an experiment.

https://user-images.githubusercontent.com/9500018/140042720-a580b2a3-8b07-4a54-9b2f-b2f01ad57026.mp4

Of course

- It works without `File explorer` plugin
- When we move the file, links related to the file are changed

If you think it is ok, I'll release it as version 1.2.0 :)

**Comment by chrisgrieser** [comment]
Looks fine to me! Thanks a lot :)

**Comment by tadashi-aikawa** [comment]
@chrisgrieser 
Thank you for quick confirm!

I have released as [v1.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/1.2.0) 🚀
