### ISSUE TITLE
[Feature Request] Option to hide / show hotkeys text inside switcher window

### ISSUE THREAD

**Issue by Glint-Eye** [tadashi-aikawa/obsidian-another-quick-switcher#80]
It would be great if the text for the hotkeys at the bottom of the switcher window could be optionally deactivated as the list is starting to get quite big and it takes up a lot of space.

cheers :)

**Comment by tadashi-aikawa** [comment]
Perfectly agree 👍

**Comment by tadashi-aikawa** [comment]
Released in v6.0.0-beta11 🚀 

[For details]
`Add a "Hide hotkey guides" option` in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78

**Comment by FelipeRearden** [comment]
> [For details]
> 
> `Add a "Hide hotkey guides" option` in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/78

@tadashi-aikawa just to let you know that in v6.0.0-beta13 ON MOBILE the option "Hide hotkey guides" is NOT hiding the numbers when the option is enable.
- I did not test on Desktop; 
- I restarted Obsidian after changing the option.

Maybe is something only on my end :)

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
It means "text for the hotkeys at the bottom". Not a number 👍

**Comment by FelipeRearden** [comment]
> @FelipeRearden 
> 
> It means "text for the hotkeys at the bottom". Not a number 👍 

Forgive me @tadashi-aikawa !!! I misunderstood "text for the hotkeys at the bottom" with "hotkeys in dialog"

Sorry for the mistake 🙏

**Comment by tadashi-aikawa** [comment]
Released in [v6.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.0.0) 🚀
