### ISSUE TITLE
[Feature Request] New Type of Priority -> Specific Tag Matches

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#81]
Hello @tadashi-aikawa !!!!

ℹ️ This FR is related to #19 

This FR is about a new type of priority related to tags. 

It's gonna be hard for to explain, let me know if something is not clear ...

**In a nutshell:**  a new priority that lets the user *define* the order by tag names that are defined by the user itself in the text field

## My Tag Structre 

I use tags for everything in my vault. 95% of my notes has al least one tag

And I have a lot of **Nested Tags** 

I gonna use a subset of of my tags to explain this FR with an example

`#Source/Book`
`#Source/Podcast`
`#Source/Video`
`#Source/Article`

`#Creator/Tim_Ferriss` 

`#Status/NotDone`

## Real Example

I wanna create a Search that ...

**RULE** 🅰️  get all notes from #Creator/Tim_Ferriss where status is #Status/NotDone

**RULE** 🅱️ Sorted by this order:
1️⃣ #Source/Podcast  
2️⃣ #Source/Book
3️⃣ #Source/Video 
4️⃣ #Source/Article 

### This is my Setup 

Default Input: `#Creator/Tim_Ferriss #Status/NotDone `  

Command Prefix: empty

Sort Priorities:
`Tag match`

Ignore prefix path patterns empty

### This is What we Get 

📸 Forgive for my poor Screenshot (I am not at my Devices, I create a simple example)

![image](https://user-images.githubusercontent.com/85180696/184502080-0a879c08-7e17-458b-9949-73891f8715d6.jpeg)

## My FR

My FR is about sorting these 4 notes based on a **secondary** tag pattern defined by the user 

A New Priority for tags where the user can type the order of secondary tags

Something like this:

`Tag Match Pattern: tag1,tag2,tag3`

From my example: 

`Tag Match Pattern: #Source/Podcast,#Source/Book,#Source/Video,#Source/Article`

---

Thanks for reading this !!!!

Let me know if something is not clear :)

Have a great day!!!!!

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @FelipeRearden :)

If I could implement it simply, I'll try it after the next release 👍

**Comment by FelipeRearden** [comment]
> Thank you for your FR, @FelipeRearden :)
> 
> 
> 
> If I could implement it simply, I'll try it after the next release 👍 

Thank you very much @tadashi-aikawa for trying to implement this FR !!!!! 

Let's hope its an easy one 🙏🙏🙏

**Comment by tadashi-aikawa** [comment]
@FelipeRearden 
Released in [7.0.0-beta1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0-beta1) 🚀

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0) 🚀
