### ISSUE TITLE
[Feature Request] Show Directory at new line on Obsidian Mobile - iPad users

### ISSUE THREAD

**Issue by FelipeRearden** [tadashi-aikawa/obsidian-another-quick-switcher#83]
Hello @tadashi-aikawa !!!

This issue is related to the option `Show Directory at new line` for Mobile users -> specially for iPad users.

More information about this issue can be seen in a comment [here](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/53#issuecomment-1216628954)

Thank you very much !!!!!

**Comment by tadashi-aikawa** [comment]
Thank you for creating!

**Comment by tadashi-aikawa** [comment]
Released in [v6.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.1.0) 🚀

**Comment by FelipeRearden** [comment]
> Released in [v6.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.1.0) 🚀 

Working perfect on version `v6.1.0` on Obsidian Mobile 1.3.0 on iPadOS.

Thank you much @tadashi-aikawa !!!!!
