### ISSUE TITLE
[FR] vim-like navigation in move file to folder switcher

### ISSUE THREAD

**Issue by kometenstaub** [tadashi-aikawa/obsidian-another-quick-switcher#84]
The title says it.

I would appreciate Vim-like navigation with Ctrl-j and Ctrl-k in the move file to folder switcher like what is already available in the recommended search switcher.

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @kometenstaub :)

Yes, I'll release it next release 👍

**Comment by tadashi-aikawa** [comment]
Released in [v6.1.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.1.0) 🚀
