### ISSUE TITLE
FR: Allow setting of hotkeys in dialogs

### ISSUE THREAD

**Issue by brimwats** [tadashi-aikawa/obsidian-another-quick-switcher#85]
I don;t use hover editor all that much, so I would love to make `open in new pane` crtl alt enter` but there is currently no way to customize those. Thanks for your amazing plugin!

**Comment by tadashi-aikawa** [comment]
Thank you for your FR, @brimwats 👍

**Comment by tim-hilde** [comment]
@tadashi-aikawa 
A similar issue arrises with 0.16 and the introduction of tabs as a new hotkey is defined by default: "cmd alt ↵" opens a link into a new pane on the right. 

It'd be nice to have the same hotkeys for opening files mirrored in this plugin. Or, in line with this FR at least give the opportunity to change the hotkeys.

**Comment by tadashi-aikawa** [comment]
@tim-hilde 
100% agree. I am going to implement it in the next major release 👍

**Comment by tadashi-aikawa** [comment]
Hi, @brimwats @tim-hilde 

I have released [v7.0.0-beta8](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0-beta8) 🚀 

To be honest, I'm not sure how it would work on macOS correctly😅. If anyone uses macOS and BRAT, it would be great to try the beta version 🙏

For details: https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/discussions/101#discussion-4357986

**Comment by tim-hilde** [comment]
@tadashi-aikawa 

Yeah, this works! Great work and thank you so much!

**Comment by tadashi-aikawa** [comment]
Released in [v7.0.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/7.0.0) 🚀

**Comment by tonygrr** [comment]
Can you tell me how to make keyboard shortcuts (for example, `ctrl+j`) work in all keyboard layouts (English and, for example, Russian)?

**Comment by tonygrr** [comment]
Can you tell me how to make keyboard shortcuts (for example, `ctrl+j`) work in all keyboard layouts (English and, for example, Russian)?

**Comment by brimwats** [comment]
that's not possible unless we're talking on the level of how a computer sees a keyboard, like `0x0c` or something. the two examples you gave; Russian doesn't use J, it uses Cyrillic. keyboard layouts are also quite different

**Comment by tadashi-aikawa** [comment]
@tonygrr 
If they have an `event.key`, it might be possible to set the shortcut keys.

![image](https://user-images.githubusercontent.com/9500018/197235079-848e8de1-d23a-4b2e-89a0-da9151c3adab.png)
![image](https://user-images.githubusercontent.com/9500018/197235172-1a116b51-8520-48fa-9971-f269a8c87ec4.png)

**Comment by tonygrr** [comment]
@tadashi-aikawa unfortunately, for Russian and English layout event.key of the same button is different.

Is it possible to improve this functionality to eliminate this problem? Before v. 7.0.0, navigation worked with any keyboard layout. Maybe there is a way to allow the user to configure multiple keyboard shortcuts for the same action?

**Comment by tadashi-aikawa** [comment]
@tonygrr
Do you use both Russian and English layouts?

> Before v. 7.0.0, navigation worked with any keyboard layout.

What is **navigation** specifically? Between 6 and 7, I didn't change most actions related to hotkeys (in dialog) except for a few ones.

**Comment by tonygrr** [comment]
> Do you use both Russian and English layouts?

Yeah. 

> Between 6 and 7, I didn't change most actions related to hotkeys (in dialog) except for a few ones.

I don't remember exactly on which version I started having problems, but at one point after updating the plugin, I stopped navigating through the search results using the `ctrl+j/k` shortcuts. I thought this was due to the introduction of the "Customizable hotkeys in dialogs" feature in v. 7.0.0.

I recorded a gif with work of plugin "Another Quick Switcher" v. 6.3.2, where you can see that keyboard shortcut `ctrl+j/k ` works with any keyboard layout (note the language switch in the lower right corner).

![another quick switcher](https://user-images.githubusercontent.com/72566774/197574743-99c7274a-3698-448d-875c-2cdccb408294.gif)

**Comment by tadashi-aikawa** [comment]
@tonygrr 
Thank you for details!

I have found the differences and a solution. I'll fix it 👍

**Comment by tadashi-aikawa** [comment]
@tonygrr 
Fixed in https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/118#issuecomment-1289794754
