### ISSUE TITLE
Question: Search query starts with :n like :n hoge

### ISSUE THREAD

**Issue by z-jason** [tadashi-aikawa/obsidian-another-quick-switcher#9]
Could you explain how to use this? I thought I should type ":n" when I open the palette but it doesn't work. Thanks!

**Comment by tadashi-aikawa** [comment]
@z-jason 
Please see https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/issues/4#issuecomment-944341917

You need to one of the `Another Quick Switcher:` command and type `:n`, `:r` or `:b`.

If you run `Another Quick Switcher: Normal search`, and want to Normal search, you need not type `:n`.

**Comment by tadashi-aikawa** [comment]
I have closed this issue because there has been no response in a couple of weeks.
