### ISSUE TITLE
Jump to Tag Search Result

### ISSUE THREAD

**Issue by Riz0** [tadashi-aikawa/obsidian-another-quick-switcher#92]
Hello @tadashi-aikawa 

Thanks for the lovely plugin. I like being able to use global tag search from quick switcher so this is great. The only issue is when I select a tag search result it highlights and jumps to the header of the note where the tag is found within, but not the tag itself. Do I have to adjust something to make it possible or does it need to be implemented? 

Also is there any way to include search results from the within the active note/file when performing a tag search? 

Ideally, when inputting a tag search query you would get results globally from all files including the active file (similar to how "headers search in file" works) and it would jump to that particular tag not to the top of the note. Thanks for any help

**Comment by tadashi-aikawa** [comment]
Hi, @Riz0 :)

First, for now, Another Quick Switcher **doesn't support tag search**. Another Quick Switcher supports file search **by tags**.

 > The only issue is when I select a tag search result it highlights and jumps to the header of the note where the tag is found within, but not the tag itself. 

Therefore, this is the intended behavior as expected.

> Also is there any way to include search results from the within the active note/file when performing a tag search?

Similarly, the purpose is to search for files, so the current file is not targeted.

Kind regards.

**Comment by Riz0** [comment]
Alrighty, thanks for the explanation.
