### ISSUE TITLE
Don't highlight the first line of the frontmatter when opening files

### ISSUE THREAD

**Issue by lguenth** [tadashi-aikawa/obsidian-another-quick-switcher#94]
Hey, @tadashi-aikawa! 
I'm not sure if this was introduced with the last major update or if I just didn't notice it before... But when opening a file, the first line of my frontmatter always gets highlighted, like a search result. Is there any way you could prevent that?

[2022-08-24 Screencap](https://user-images.githubusercontent.com/69049131/186383315-399edbd9-c224-4f52-88e8-be39d80d1a0c.webm)

**Comment by tadashi-aikawa** [comment]
Hi, @lguenth. Thank you for your report :)

It seems to be a bug. I'll fix it 👍

**Comment by tadashi-aikawa** [comment]
Released in [v6.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.2.0) 🚀

**Comment by FelipeRearden** [comment]
> Released in [v6.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.2.0) 🚀 

Working perfect on version [v6.2.0](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.2.0) on Obsidian Mobile 1.3.1 on iPadOS 15

Thank you very much @tadashi-aikawa !!!!!!!
