### ISSUE TITLE
[BUG]: Minor issues with 0.16

### ISSUE THREAD

**Issue by chrisgrieser** [tadashi-aikawa/obsidian-another-quick-switcher#98]
Text input fields have minor breaks with the new default theme now: 
<img width="967" alt="image" src="https://user-images.githubusercontent.com/73286100/187448949-325add9c-d45a-45bf-95ca-4ef993b9eb80.png">

**Comment by tadashi-aikawa** [comment]
Thanks!  But I didn't reproduce it 🤔 

![image](https://user-images.githubusercontent.com/9500018/187449759-ad12579d-259d-425b-a650-92f244b7c2de.png)

On mobile? (ex: iPad)

**Comment by chrisgrieser** [comment]
Nope, happens on desktop. I looked into it, it seems the issue occurs because I have increased zoom level (`ctrl/cmd +`) a bit. With reduced zoom level (`ctrl/cmd –`) the issue does not occur anymore.

I assume it is because of some `min-width` you have for those text fields somewhere?

**Comment by tadashi-aikawa** [comment]
Sure. `styles.css` specifies `width: 500px;`.

I think the default theme of Obsidian v0.16.0 shows more information than v0.15, So I'll reduce or not set the width

**Comment by tadashi-aikawa** [comment]
Released in [v6.3.1](https://github.com/tadashi-aikawa/obsidian-another-quick-switcher/releases/tag/6.3.1) 🚀 

@chrisgrieser 
Please confirm it 🙏

**Comment by chrisgrieser** [comment]
can confirm, looks good now 🙏
